from typing import Protocol

from app.schemas import CreateSpeakerSessionRequest, SpeakerAudioFrame, SpeakerSpan


class SpeakerEngine(Protocol):
    async def create_session(self, request: CreateSpeakerSessionRequest) -> None: ...
    async def push_audio(self, frame: SpeakerAudioFrame) -> list[SpeakerSpan]: ...
    async def flush(self, session_id: str) -> list[SpeakerSpan]: ...
    async def close_session(self, session_id: str) -> None: ...
