// Generated from frozen v1.0 898ee517e7aac00b03bc79ff2d0597dd00fdbf56; no new correction rules.
// Hidden cultivation rules are retained in the rule library but are not activated by visible phone profiles.
const asrDomainProtectedTerms = <String, List<String>>{
  "product": [
    "同传",
    "同声传译",
    "字幕",
    "端侧",
    "端侧 ASR",
    "在线模式",
    "断句",
    "语义组句",
    "会议纪要",
    "自动识别语言",
    "自动反向",
    "Qwen3 ASR",
    "FireRedASR2",
    "Hy-MT2",
    "VoxCPM2",
    "苟到化形",
    "A-120",
    "iPhone 14",
    "on-device ASR",
    "在线模型链路",
    "online model pipeline",
    "simultaneous interpretation",
    "meeting minutes",
    "automatic language detection",
    "auto reverse translation"
  ],
  "business": [
    "会议纪要",
    "meeting minutes",
    "行动项",
    "action item",
    "待办事项",
    "to-do item",
    "截止时间",
    "deadline",
    "预算",
    "budget",
    "报价",
    "quotation",
    "合同",
    "contract",
    "发票",
    "invoice",
    "付款方式",
    "payment method",
    "回款",
    "payment collection",
    "客单价",
    "average order value",
    "转化率",
    "conversion rate",
    "毛利率",
    "gross margin",
    "交付周期",
    "delivery cycle",
    "项目排期",
    "project timeline",
    "风险点",
    "risk item"
  ],
  "technology": [
    "人工智能",
    "artificial intelligence",
    "大语言模型",
    "large language model",
    "语音识别",
    "speech recognition",
    "语音合成",
    "speech synthesis",
    "模型部署",
    "model deployment",
    "在线推理",
    "online inference",
    "端侧推理",
    "on-device inference",
    "接口",
    "API",
    "网关",
    "gateway",
    "微服务",
    "microservice",
    "容器",
    "container",
    "数据库",
    "database",
    "缓存",
    "cache",
    "日志",
    "logs",
    "链路追踪",
    "distributed tracing",
    "延迟",
    "latency",
    "吞吐量",
    "throughput",
    "并发",
    "concurrency",
    "故障恢复",
    "failure recovery",
    "灰度发布",
    "gray release"
  ],
  "medical": [
    "挂号",
    "registration",
    "门诊",
    "outpatient clinic",
    "急诊",
    "emergency department",
    "病历",
    "medical record",
    "处方",
    "prescription",
    "化验单",
    "lab report",
    "影像检查",
    "imaging exam",
    "超声",
    "ultrasound",
    "报告",
    "report",
    "复查",
    "follow-up exam",
    "过敏史",
    "allergy history",
    "用药剂量",
    "medication dosage",
    "副作用",
    "side effect",
    "禁忌症",
    "contraindication",
    "血压",
    "blood pressure",
    "血糖",
    "blood glucose",
    "体温",
    "body temperature",
    "甲状腺",
    "thyroid",
    "结节",
    "nodule",
    "医保",
    "medical insurance"
  ],
  "travel": [
    "护照",
    "passport",
    "签证",
    "visa",
    "登机牌",
    "boarding pass",
    "值机",
    "check-in",
    "行李托运",
    "checked baggage",
    "登机口",
    "boarding gate",
    "中转",
    "transfer",
    "延误",
    "delay",
    "酒店预订",
    "hotel reservation",
    "入住",
    "退房",
    "check-out",
    "押金",
    "deposit",
    "景点门票",
    "attraction ticket",
    "导游",
    "tour guide",
    "免税店",
    "duty-free shop"
  ],
  "dining": [
    "菜单",
    "menu",
    "预约",
    "reservation",
    "排队取号",
    "queue number",
    "招牌菜",
    "signature dish",
    "套餐",
    "set meal",
    "过敏原",
    "allergen",
    "花生过敏",
    "peanut allergy",
    "不吃辣",
    "not spicy",
    "微辣",
    "mildly spicy",
    "少油少盐",
    "less oil and less salt",
    "打包",
    "take away",
    "买单",
    "check, please",
    "开发票",
    "issue an invoice",
    "服务费",
    "service charge",
    "小费",
    "tip"
  ],
  "entertainment": [
    "演唱会",
    "concert",
    "电影票",
    "movie ticket",
    "座位号",
    "seat number",
    "检票口",
    "ticket gate",
    "入场时间",
    "entry time",
    "字幕",
    "subtitles",
    "配音",
    "dubbing",
    "预告片",
    "trailer",
    "直播",
    "live stream",
    "弹幕",
    "live comments",
    "会员",
    "membership",
    "包厢",
    "private room",
    "剧本杀",
    "murder mystery game",
    "桌游",
    "board game",
    "周边",
    "merchandise"
  ],
};
