const iconPair = (name: string) => ({ outlined: name, filled: name } as const);

export const enterpriseIcons = {
  navigation: {
    dashboard: iconPair("dashboard"),
    campaigns: iconPair("campaign"),
    support: iconPair("support_agent"),
    meetings: iconPair("groups"),
    contacts: iconPair("contacts"),
    knowledge: iconPair("menu_book"),
    analytics: iconPair("query_stats"),
    audit: iconPair("policy"),
    settings: iconPair("settings"),
  },
  action: {
    create: "add",
    search: "search",
    filter: "filter_alt",
    refresh: "refresh",
    import: "upload_file",
    export: "download",
    more: "more_horiz",
    approve: "verified_user",
    takeover: "pan_tool_alt",
    shareScreen: "screen_share",
    stopShare: "stop_screen_share",
    publish: "publish",
    review: "fact_check",
    version: "history",
    edit: "edit",
  },
  member: {
    person: "person",
    role: "admin_panel_settings",
  },
  content: {
    source: "description",
    terms: "translate",
    script: "record_voice_over",
  },
  meeting: {
    materials: "article",
    transcript: "subject",
    summary: "summarize",
    evidence: "link",
    action: "task_alt",
    end: "stop_circle",
    calendar: "event",
    calendarSync: "sync",
    openExternal: "open_in_new",
  },
  support: {
    queue: "inbox",
    transcript: "closed_caption",
    customer: "person",
    knowledge: "menu_book",
    risk: "shield",
    actions: "task_alt",
    aiStopped: "voice_over_off",
    mute: "mic_off",
    transfer: "swap_horiz",
    endCall: "call_end",
    ticket: "confirmation_number",
    callback: "phone_callback",
  },
  settings: {
    members: "group",
    billing: "workspace_premium",
    region: "public",
    provider: "hub",
    usage: "data_usage",
    budget: "speed",
    entitlement: "verified",
  },
  dashboard: {
    tenant: "domain",
    provider: "hub",
    plan: "workspace_premium",
    alert: "notifications_active",
    tasks: "checklist",
    business: "account_tree",
    trace: "timeline",
  },
  audit: {
    events: "policy",
    details: "manage_search",
    export: "download",
    analytics: "query_stats",
  },
  quality: {
    dashboard: "fact_check",
    rules: "rule",
    analyze: "manage_search",
    evidence: "find_in_page",
    answer: "record_voice_over",
    tools: "construction",
  },
  campaign: {
    aggregate: "campaign",
    objective: "track_changes",
    countries: "public",
    languages: "translate",
    schedule: "event",
    concurrency: "speed",
    approval: "verified_user",
    edit: "edit",
    leads: "contacts",
    import: "upload_file",
    rollback: "undo",
    consent: "verified_user",
    evidence: "attach_file",
    revoke: "block",
    suppression: "block",
    globalSuppression: "public",
    countryPolicy: "policy",
    localTime: "schedule",
    voicemail: "voicemail",
    validate: "fact_check",
    approve: "verified",
    reject: "cancel",
    scheduler: "pending_actions",
    claim: "lock_clock",
    pstn: "phone_in_talk",
    agent: "smart_toy",
    disclosure: "campaign",
    monitoring: "monitor_heart",
    captions: "closed_caption",
    risk: "warning",
    latency: "timer",
    failure: "error_outline",
    outcome: "assignment_turned_in",
    nextAction: "task_alt",
  },
  appearance: {
    system: "brightness_auto",
    light: "light_mode",
    dark: "dark_mode",
  },
  guest: {
    privateMeeting: "lock",
    devices: "devices",
    microphone: "mic",
    captions: "closed_caption",
  },
  status: {
    loading: "autorenew",
    empty: "inbox",
    not_ready: "construction",
    degraded: "warning",
    forbidden: "lock",
    conflict: "sync_problem",
    processing: "pending",
    failed: "error_outline",
  },
} as const;

export type EnterpriseNavigationIcon = keyof typeof enterpriseIcons.navigation;
