import 'app_billing_localization_texts.dart';
import 'app_call_link_localization_texts.dart';
import 'app_history_localization_texts.dart';
import 'app_scan_localization_texts.dart';
import 'app_voice_profile_localization_texts.dart';

const appLocalizationTexts = <String, Map<String, String>>{
  ...appBillingLocalizationTexts,
  ...appCallLinkLocalizationTexts,
  ...appHistoryLocalizationTexts,
  ...appScanLocalizationTexts,
  ...appVoiceProfileLocalizationTexts,
  'appTitle': {'zh': 'ai phone', 'en': 'ai phone'},
  'realtimeSubtitle': {
    'zh': '中英实时同声传译',
    'en': 'Chinese-English realtime interpretation',
  },
  'deviceAsrDiagnostics': {'zh': '模型链路诊断', 'en': 'Model pipeline diagnostics'},
  'refresh': {'zh': '刷新', 'en': 'Refresh'},
  'clear': {'zh': '清除', 'en': 'Clear'},
  'search': {'zh': '搜索', 'en': 'Search'},
  'language': {'zh': '语言', 'en': 'Language'},
  'chinese': {'zh': '中文', 'en': 'Chinese'},
  'english': {'zh': '英文', 'en': 'English'},
  'translationDirection': {'zh': '翻译方向', 'en': 'Translation direction'},
  'translateToChinese': {'zh': '英译中', 'en': 'English to Chinese'},
  'translateToEnglish': {'zh': '中译英', 'en': 'Chinese to English'},
  'start': {'zh': '开始', 'en': 'Start'},
  'pause': {'zh': '暂停', 'en': 'Pause'},
  'resume': {'zh': '继续', 'en': 'Resume'},
  'startAgain': {'zh': '再次开始', 'en': 'Start again'},
  'end': {'zh': '结束', 'en': 'End'},
  'currentSubtitle': {'zh': '当前句', 'en': 'Current'},
  'translationPending': {'zh': '翻译中', 'en': 'Translating'},
  'backToLatest': {'zh': '回到底部', 'en': 'Back to latest'},
  'overlappingSpeech': {'zh': '多人同时说话', 'en': 'Overlapping speech'},
  'mixedLanguage': {'zh': '中英混合', 'en': 'Mixed language'},
  'tapStartToBegin': {'zh': '点击开始进行同传', 'en': 'Tap start to begin'},
  'export': {'zh': '导出', 'en': 'Export'},
  'exportDiagnostics': {'zh': '导出诊断', 'en': 'Export diagnostics'},
  'diagnosticsReportReady': {
    'zh': '诊断报告已生成',
    'en': 'Diagnostics report ready',
  },
  'exportMarkdown': {'zh': 'Markdown', 'en': 'Markdown'},
  'exportText': {'zh': '纯文本', 'en': 'TXT'},
  'exportJson': {'zh': 'JSON', 'en': 'JSON'},
  'exportCsv': {'zh': 'CSV', 'en': 'CSV'},
  'delete': {'zh': '删除', 'en': 'Delete'},
  'open': {'zh': '打开', 'en': 'Open'},
  'cancel': {'zh': '取消', 'en': 'Cancel'},
  'prepareModel': {'zh': '准备模型', 'en': 'Prepare model'},
  'inspectModel': {'zh': '检查模型', 'en': 'Inspect model'},
  'checkService': {'zh': '检查服务', 'en': 'Check service'},
  'serviceConnection': {'zh': '服务连接', 'en': 'Service connection'},
  'onDeviceTranslation': {'zh': '端侧翻译', 'en': 'On-device translation'},
  'apiBaseUrl': {'zh': 'API 地址', 'en': 'API URL'},
  'apiHealthStatus': {'zh': 'API 状态', 'en': 'API status'},
  'warning': {'zh': '提示', 'en': 'Warning'},
  'localAddressWarning': {
    'zh': '真机请连接统一服务器地址，不能使用手机本机地址',
    'en':
        'Use the unified server URL on a physical device, not a local-only address',
  },
  'apiService': {'zh': '服务名称', 'en': 'Service'},
  'serviceVersion': {'zh': '服务版本', 'en': 'Version'},
  'realtimeWsEndpoint': {'zh': '实时网关地址', 'en': 'Realtime Gateway URL'},
  'gatewayHealthStatus': {'zh': '网关状态', 'en': 'Gateway status'},
  'gatewayService': {'zh': '网关服务', 'en': 'Gateway service'},
  'gatewayProvider': {'zh': '实时翻译提供方', 'en': 'Realtime provider'},
  'gatewayResolvedProvider': {'zh': '实际翻译链路', 'en': 'Resolved provider'},
  'gatewayAsrProvider': {'zh': 'ASR 提供方', 'en': 'ASR provider'},
  'gatewaySessionEventSink': {'zh': '历史同步模式', 'en': 'History sync mode'},
  'notChecked': {'zh': '未检查', 'en': 'Not checked'},
  'microphoneSelfTest': {'zh': '麦克风 ASR 自测', 'en': 'Microphone ASR self-test'},
  'startSelfTest': {'zh': '开始自测', 'en': 'Start self-test'},
  'stopSelfTest': {'zh': '停止自测', 'en': 'Stop self-test'},
  'selfTestResults': {'zh': '自测结果', 'en': 'Self-test results'},
  'selfTestNoResult': {'zh': '尚未收到识别结果', 'en': 'No recognition result yet'},
  'audioInputStats': {'zh': '音频输入统计', 'en': 'Audio input stats'},
  'audioNoInputHint': {
    'zh': '未收到麦克风输入。请确认已允许麦克风权限，并对着 iPhone 麦克风说一句话。',
    'en':
        'No microphone input received. Allow microphone access and speak into the iPhone microphone.',
  },
  'audioNoConvertedSamplesHint': {
    'zh': '已收到麦克风输入，但采样转换没有输出。请检查输入采样率和声道。',
    'en':
        'Microphone input was received, but sample conversion produced no output. Check input sample rate and channels.',
  },
  'audioConversionFailureHint': {
    'zh': '已收到麦克风输入，但 iOS 音频格式转换失败。请查看最近转换错误，并重新开始自测。',
    'en':
        'Microphone input was received, but iOS audio format conversion failed. Check the last conversion error and restart the self-test.',
  },
  'audioSessionErrorHint': {
    'zh': 'iOS 音频会话启动失败。请检查麦克风权限、系统音频路由，并重新开始自测。',
    'en':
        'The iOS audio session failed to start. Check microphone permission, system audio routing, and restart the self-test.',
  },
  'asrProcessingErrorHint': {
    'zh': 'ASR 模型处理音频失败。请检查模型包、运行时状态，并重新开始自测。',
    'en':
        'The ASR model failed while processing audio. Check the model bundle, runtime status, and restart the self-test.',
  },
  'audioNoAsrChunksHint': {
    'zh': '已收到音频，但尚未形成 ASR 音频块。请继续说一句完整短句，或等待模型窗口结束。',
    'en':
        'Audio was received, but no ASR chunk has been emitted yet. Keep speaking a short sentence or wait for the model window.',
  },
  'finalResult': {'zh': '最终', 'en': 'Final'},
  'partialResult': {'zh': '临时', 'en': 'Partial'},
  'allowModelDownload': {'zh': '允许下载模型', 'en': 'Allow model download'},
  'availability': {'zh': '可用性', 'en': 'Availability'},
  'nativeDetails': {'zh': '原生状态', 'en': 'Native details'},
  'lastError': {'zh': '最近错误', 'en': 'Last error'},
  'ready': {'zh': '已就绪', 'en': 'Ready'},
  'notReady': {'zh': '未就绪', 'en': 'Not ready'},
  'yes': {'zh': '是', 'en': 'Yes'},
  'no': {'zh': '否', 'en': 'No'},
  'unknown': {'zh': '未知', 'en': 'Unknown'},
  'statusIdle': {'zh': '待开始', 'en': 'Idle'},
  'statusConnecting': {'zh': '连接中', 'en': 'Connecting'},
  'statusListening': {'zh': '同传中', 'en': 'Listening'},
  'statusPaused': {'zh': '已暂停', 'en': 'Paused'},
  'statusEnding': {'zh': '正在结束', 'en': 'Ending'},
  'statusEnded': {'zh': '已结束', 'en': 'Ended'},
  'statusFailed': {'zh': '已中断', 'en': 'Failed'},
  'tabLive': {'zh': '同传', 'en': 'Live'},
  'tabCall': {'zh': '通话', 'en': 'Calls'},
  'tabLens': {'zh': '扫描', 'en': 'Lens'},
  'tabRecords': {'zh': '记录', 'en': 'Records'},
  'tabMe': {'zh': '我的', 'en': 'Me'},
  'scanTitle': {'zh': '拍照翻译', 'en': 'Scan translation'},
  'scanDomesticBody': {
    'zh': '拍照或从相册选择菜单、截图、合同和表格，端侧 OCR 识别后自动中英互译。',
    'en': 'Scan menus, screenshots, contracts, and forms for OCR translation.',
  },
  'dataRegion': {'zh': '数据区域', 'en': 'Data region'},
  'regionEdition': {'zh': '区域版本', 'en': 'Region edition'},
  'callProviderPolicy': {'zh': '通话策略', 'en': 'Call policy'},
  'complianceProfile': {'zh': '合规档案', 'en': 'Compliance profile'},
  'modelProviders': {'zh': '模型提供方', 'en': 'Model providers'},
  'paymentStack': {'zh': '支付方式', 'en': 'Payment stack'},
  'domesticEditionStatus': {
    'zh': '国内版 · 中英优先 · PSTN 暂未开放',
    'en': 'Domestic edition · Chinese-English first · PSTN not enabled',
  },
  'internationalEditionStatus': {
    'zh': '国际版 · 多地区服务 · PSTN 可配置',
    'en': 'International edition · Multi-region services · PSTN configurable',
  },
  'typeToSpeak': {'zh': '输入并朗读', 'en': 'Type-to-Speak'},
  'typeToSpeakBody': {
    'zh': '输入姓名、地址、数字等内容，自动翻译后用系统语音读出。',
    'en': 'Type names, addresses, or numbers and read the translation aloud.',
  },
  'typeToSpeakInput': {'zh': '输入内容', 'en': 'Text to translate'},
  'translate': {'zh': '翻译', 'en': 'Translate'},
  'speakTranslation': {'zh': '朗读译文', 'en': 'Speak translation'},
  'saveToHistory': {'zh': '保存记录', 'en': 'Save'},
  'stopSpeaking': {'zh': '停止朗读', 'en': 'Stop speaking'},
  'translatedText': {'zh': '译文', 'en': 'Translation'},
  'typeToSpeakNoTranslation': {'zh': '暂无译文', 'en': 'No translation yet'},
  'type_to_speak_empty': {'zh': '请输入要翻译的内容', 'en': 'Enter text first'},
  'type_to_speak_translation_unavailable': {
    'zh': '翻译暂不可用，请稍后重试',
    'en': 'Translation is unavailable. Try again later.',
  },
  'type_to_speak_speech_unavailable': {
    'zh': '系统朗读暂不可用',
    'en': 'System speech is unavailable.',
  },
  'type_to_speak_saved': {
    'zh': '已保存到记录',
    'en': 'Saved to history.',
  },
  'type_to_speak_save_failed': {
    'zh': '保存失败，请稍后重试',
    'en': 'Could not save. Try again later.',
  },
  'talkMode': {'zh': '对话', 'en': 'Talk'},
  'listeningMode': {'zh': '聆听', 'en': 'Listening'},
};

const zhDiagnosticsLabels = <String, String>{
  'canStart': '可启动',
  'reason': '原因',
  'message': '状态消息',
  'localModelReady': '本地模型',
  'preparedModelReady': '已加载模型',
  'decoderReady': '解码器',
  'audio.running': '录音运行中',
  'audio.sessionActive': '音频会话',
  'audio.sessionError': '音频会话错误',
  'audio.processingError': 'ASR 处理错误',
  'audio.pendingSamples': '待处理采样',
  'audio.inputBuffers': '输入缓冲数',
  'audio.inputSamples': '输入采样数',
  'audio.convertedSamples': '转换采样数',
  'audio.conversionFailures': '转换失败次数',
  'audio.floatExtractionFailures': '浮点采样提取失败',
  'audio.emittedChunks': 'ASR 音频块数',
  'audio.flushedTailSamples': '已刷新尾段采样',
  'audio.lastConversionError': '最近转换错误',
  'audio.lastChunkRms': '最近音量 RMS',
  'audio.inputSampleRate': '输入采样率',
  'audio.inputChannels': '输入声道数',
  'audio.tapInstalled': '音频输入监听',
  'microphone.permission': '麦克风权限',
  'fluidAudio.runtimeAvailable': 'FluidAudio 运行时',
  'fluidAudio.prepared': 'FluidAudio 模型已加载',
  'fluidAudio.model.lastResolvedPath': '最近解析路径',
  'fluidAudio.model.lastResolution': '最近解析结果',
  'fluidAudio.audio.sessionActive': '音频会话',
  'fluidAudio.audio.sessionError': '音频会话错误',
  'fluidAudio.processingError': 'ASR 处理错误',
  'fluidAudio.audio.tapInstalled': '音频输入监听',
  'model.path': '模型路径',
  'model.root': '模型根目录',
  'modelScan.candidateCount': '候选路径数',
  'modelScan.selectedRoot': '选中模型路径',
  'modelScan.selectedStatus': '模型扫描状态',
  'modelScan.selectedLayout': '选中模型布局',
  'modelScan.selectedMissing': '缺失组件',
  'modelScan.reports': '扫描明细',
  'translation.available': '端侧翻译可用',
  'translation.provider': '翻译提供方',
  'translation.sourceLanguage': '源语言',
  'translation.targetLanguage': '目标语言',
  'translation.status': '翻译状态',
  'translation.reason': '翻译原因',
  'translation.message': '翻译消息',
  'gateway.asrEndpoint': 'ASR 端点',
  'gateway.asrHealthUrl': 'ASR 健康检查',
  'gateway.translationEndpoint': '翻译端点',
  'gateway.translationModel': '翻译模型',
};

const zhDiagnosticsValues = <String, String>{
  'ready': '已就绪',
  'ok': '正常',
  'model_not_found': '模型未找到',
  'model_incomplete': '模型不完整',
  'missing': '缺失',
  'fluid_split_fused': 'FluidAudio 融合解码布局',
  'split_encoder_decoder_joint': '编码器/解码器/联合网络分离布局',
  'fluidaudio_unavailable': 'FluidAudio 不可用',
  'downloaded_or_cached': '已下载或已缓存',
  'local': '本地模型',
  'not_started': '未开始',
  'microphone_permission_denied': '麦克风权限已拒绝',
  'undetermined': '尚未请求',
  'denied': '已拒绝',
  'granted': '已授权',
  'unsupported_platform': '当前平台不支持',
  'system_asr_unavailable': '系统语音识别不可用',
  'android_system_asr': 'Android 系统 ASR',
  'mock': '模拟服务',
  'http': 'HTTP 服务',
  'api': 'API 历史同步',
  'lmstudio': 'LM Studio',
  'self_hosted': '自部署链路',
  'qwen_live': 'Qwen LiveTranslate',
  'tencent_trtc': '腾讯 TRTC',
  'domestic': '国内版',
  'international': '国际版',
  'call_link_only': '仅通话链接',
  'pstn_enabled': '可用 PSTN 桥接',
  'pipl': '个人信息保护法',
  'us_ca': '美国/加拿大',
  'time': '时间',
  'money': '金额',
  'todo': '待办',
  'location': '地点',
  'coreml_nemotron': 'Core ML Nemotron',
  'none': '无',
  'converter_unavailable': '转换器不可用',
  'no_microphone_input': '未收到麦克风输入',
  'audio_conversion_failed': '音频转换失败',
  'no_converted_samples': '未输出转换采样',
  'no_asr_chunks': '尚未形成 ASR 音频块',
  'audio_session_error': '音频会话错误',
  'asr_processing_error': 'ASR 处理错误',
  'ios_system': 'iOS 系统翻译',
  'phrasebook': '短语兜底',
  'unavailable': '不可用',
  'installed': '已安装',
  'supported': '支持但未安装',
  'unsupported': '不支持',
  'unknown': '未知',
  'zh': '中文',
  'en': '英文',
  'auto': '自动',
  'language_pair_not_installed': '语言包未安装',
  'ios_translation_requires_ios_26': '需要 iOS 26 或更新系统',
  'on_device_translation_unavailable': '端侧翻译不可用',
  'on_device_translation_disabled': '未启用端侧翻译',
  'translation_diagnostics_unavailable': '翻译诊断不可用',
  'unsupported_language_pair': '不支持的语言对',
  'missing_plugin': '原生插件未注册',
};

const zhRuntimeMessages = <String, String>{
  'Preparing device ASR model': '正在准备端侧 ASR 模型',
  'Device ASR ready': '端侧 ASR 已就绪',
  'Android system ASR ready': 'Android 系统 ASR 已就绪',
  'Device ASR will download Nemotron model on start':
      '启动时将下载 Nemotron 端侧 ASR 模型',
  'Device ASR model ready. Connecting realtime session':
      '端侧 ASR 模型已就绪，正在连接实时会话',
  'Device ASR model ready. Starting local session': '端侧 ASR 模型已就绪，正在启动本地会话',
  'Restarting device ASR': '正在重启端侧 ASR',
  'Starting device ASR self-test': '正在启动端侧 ASR 自测',
  'Listening for ASR segments': '正在监听端侧 ASR 识别结果',
  'Device ASR self-test stopped': '端侧 ASR 自测已停止',
  'Device ASR self-test finished': '端侧 ASR 自测已完成',
  'Diagnostics report ready': '诊断报告已生成',
  'Session time limit reached': '本次会话已达到时长上限',
  'Realtime provider error': '实时翻译服务出错',
  'Realtime connection lost': '实时连接已断开',
  'Realtime connection restored': '实时连接已恢复',
  'Translation unavailable': '翻译暂不可用',
  'On-device translation unavailable': '端侧翻译暂不可用',
  'Nemotron Core ML model was not found': '未找到 Nemotron Core ML 模型',
  'Nemotron model bundle is incomplete for FluidAudio':
      'Nemotron 模型包缺少 FluidAudio 所需文件',
  'Nemotron FluidAudio model bundle was not found or is incomplete':
      '未找到 Nemotron FluidAudio 模型包，或模型包不完整',
  'FluidAudio runtime is not linked into this build': '当前构建未链接 FluidAudio 运行时',
  'FluidAudio Swift package is not linked into the iOS target':
      '当前 iOS Target 未链接 FluidAudio Swift 包',
  'System ASR is not implemented for this platform': '当前平台暂未实现系统 ASR',
  'Android system speech recognition is unavailable': 'Android 系统语音识别不可用',
  'Device ASR provider is not configured': '端侧 ASR Provider 未配置',
  'device ASR start failed': '端侧 ASR 启动失败',
  'native start failed': '端侧 ASR 启动失败',
  'Microphone permission was denied': '麦克风权限已被拒绝',
  'Microphone permission is required for device ASR': '端侧 ASR 需要麦克风权限',
  'Nemotron manager was not prepared': 'Nemotron 管理器尚未准备完成',
};
