#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REMOTE_HOST="${REMOTE_HOST:-beelink@100.110.127.117}"
REMOTE_ROOT="${REMOTE_ROOT:-/data/models/ai-phone-server}"
REMOTE_SOURCE="$REMOTE_ROOT/source"
REMOTE_RUNTIME="$REMOTE_ROOT/runtime"
AI_PHONE_DEPLOY_PROFILE="${AI_PHONE_DEPLOY_PROFILE:-test}"
case "$AI_PHONE_DEPLOY_PROFILE" in
  test|production) ;;
  *)
    echo "AI_PHONE_DEPLOY_PROFILE must be test or production" >&2
    exit 2
    ;;
esac
PUBLIC_HOST="${PUBLIC_HOST:-100.110.127.117}"
INTERNAL_SERVICE_HOST="${INTERNAL_SERVICE_HOST:-127.0.0.1}"
DEFAULT_APP_BIND_HOST="${DEFAULT_APP_BIND_HOST:-0.0.0.0}"
if [[ "$AI_PHONE_DEPLOY_PROFILE" == "production" ]]; then
  DEFAULT_APP_BIND_HOST="${DEFAULT_APP_BIND_HOST_PRODUCTION:-127.0.0.1}"
fi
API_BIND_HOST="${API_BIND_HOST:-$DEFAULT_APP_BIND_HOST}"
REALTIME_BIND_HOST="${REALTIME_BIND_HOST:-$DEFAULT_APP_BIND_HOST}"
LIVEKIT_AGENT_BIND_HOST="${LIVEKIT_AGENT_BIND_HOST:-$DEFAULT_APP_BIND_HOST}"
VOICE_AGENT_BIND_HOST="${VOICE_AGENT_BIND_HOST:-$DEFAULT_APP_BIND_HOST}"
SRT_INGRESS_BIND_HOST="${SRT_INGRESS_BIND_HOST:-127.0.0.1}"
TRANSLATION_WORKER_AUDIO_FRAME_SINK_HOST="${TRANSLATION_WORKER_AUDIO_FRAME_SINK_HOST:-$DEFAULT_APP_BIND_HOST}"
TRANSLATION_WORKER_AUDIO_FRAME_SIZE_MS="${TRANSLATION_WORKER_AUDIO_FRAME_SIZE_MS:-200}"
TRANSLATION_WORKER_AUDIO_INGEST_MAX_FRAMES="${TRANSLATION_WORKER_AUDIO_INGEST_MAX_FRAMES:-40}"
API_TRUST_PROXY_ADDRESSES="${API_TRUST_PROXY_ADDRESSES:-127.0.0.1,::1}"
REALTIME_TRUST_PROXY_ADDRESSES="${REALTIME_TRUST_PROXY_ADDRESSES:-127.0.0.1,::1}"
API_PORT="${API_PORT:-3110}"
REALTIME_PORT="${REALTIME_PORT:-3111}"
LIVEKIT_AGENT_PORT="${LIVEKIT_AGENT_PORT:-8081}"
VOICE_AGENT_PORT="${VOICE_AGENT_PORT:-8082}"
SRT_INGRESS_PORT="${SRT_INGRESS_PORT:-3310}"
ASR_SERVICE_HOST="${ASR_SERVICE_HOST:-$PUBLIC_HOST}"
SPEAKER_SERVICE_HOST="${SPEAKER_SERVICE_HOST:-$PUBLIC_HOST}"
TRANSLATION_SERVICE_HOST="${TRANSLATION_SERVICE_HOST:-$PUBLIC_HOST}"
TTS_SERVICE_HOST="${TTS_SERVICE_HOST:-$PUBLIC_HOST}"
LLM_SERVICE_HOST="${LLM_SERVICE_HOST:-$PUBLIC_HOST}"
CALL_HTTPS_DOMAIN="${CALL_HTTPS_DOMAIN:-beelink.tail1e9cec.ts.net}"
CALL_PUBLIC_BASE_URL="${CALL_PUBLIC_BASE_URL:-https://$CALL_HTTPS_DOMAIN}"
CALL_LIVEKIT_URL="${CALL_LIVEKIT_URL:-wss://$CALL_HTTPS_DOMAIN}"
API_BASE_URL="${API_BASE_URL:-http://$INTERNAL_SERVICE_HOST:$API_PORT}"
if [[ "$AI_PHONE_DEPLOY_PROFILE" == "production" && -z "${REALTIME_WS_ENDPOINT:-}" ]]; then
  REALTIME_WS_ENDPOINT=""
else
  REALTIME_WS_ENDPOINT="${REALTIME_WS_ENDPOINT:-ws://$PUBLIC_HOST:$REALTIME_PORT/realtime}"
fi
if [[ "$AI_PHONE_DEPLOY_PROFILE" == "production" && -z "$REALTIME_WS_ENDPOINT" ]]; then
  echo "Production profile requires an explicit REALTIME_WS_ENDPOINT=wss://..." >&2
  exit 2
fi
realtime_ws_authority="${REALTIME_WS_ENDPOINT#*://}"
REALTIME_ALLOWED_HOSTS="${REALTIME_ALLOWED_HOSTS:-${realtime_ws_authority%%/*},$INTERNAL_SERVICE_HOST:$REALTIME_PORT}"
REALTIME_ALLOW_NON_BROWSER_CLIENTS_WITHOUT_ORIGIN="${REALTIME_ALLOW_NON_BROWSER_CLIENTS_WITHOUT_ORIGIN:-true}"
PUBLIC_RATE_LIMIT_REDIS_URL="${PUBLIC_RATE_LIMIT_REDIS_URL:-redis://127.0.0.1:6379/1}"
SRT_INGRESS_BRIDGE_BASE_URL="${SRT_INGRESS_BRIDGE_BASE_URL:-http://$INTERNAL_SERVICE_HOST:$SRT_INGRESS_PORT}"
ASR_HTTP_ENDPOINT="${ASR_HTTP_ENDPOINT:-http://$ASR_SERVICE_HOST:8021/asr/transcribe}"
ASR_HTTP_FLUSH_ENDPOINT="${ASR_HTTP_FLUSH_ENDPOINT:-http://$ASR_SERVICE_HOST:8021/asr/sessions/:sessionId/flush}"
ASR_STREAM_ENDPOINT="${ASR_STREAM_ENDPOINT:-ws://$ASR_SERVICE_HOST:8021/asr/stream}"
ASR_HTTP_HEALTH_URL="${ASR_HTTP_HEALTH_URL:-http://$ASR_SERVICE_HOST:8021/health}"
SPEAKER_HTTP_BASE_URL="${SPEAKER_HTTP_BASE_URL:-http://$SPEAKER_SERVICE_HOST:8022}"
VOICE_IDENTITY_HTTP_BASE_URL="${VOICE_IDENTITY_HTTP_BASE_URL:-$SPEAKER_HTTP_BASE_URL}"
TRANSLATION_BASE_URL="${TRANSLATION_BASE_URL:-http://$TRANSLATION_SERVICE_HOST:8003/v1}"
TTS_HTTP_ENDPOINT="${TTS_HTTP_ENDPOINT:-http://$TTS_SERVICE_HOST:8002/tts/synthesize}"
TTS_STREAM_ENDPOINT="${TTS_STREAM_ENDPOINT:-http://$TTS_SERVICE_HOST:8002/tts/stream}"
TTS_WARMUP_ENDPOINT="${TTS_WARMUP_ENDPOINT:-http://$TTS_SERVICE_HOST:8002/tts/warmup}"
TTS_READINESS_URL="${TTS_READINESS_URL:-http://$TTS_SERVICE_HOST:8002/health}"
LLM_BASE_URL="${LLM_BASE_URL:-http://$LLM_SERVICE_HOST:1234/v1}"
LIVEKIT_WORKER_URL="${LIVEKIT_WORKER_URL:-ws://127.0.0.1:7880}"
API_STATUS_URL="${API_STATUS_URL:-http://$PUBLIC_HOST:$API_PORT/health}"
GATEWAY_STATUS_URL="${GATEWAY_STATUS_URL:-http://$PUBLIC_HOST:$REALTIME_PORT/health}"
TRANSLATION_AGENT_STATUS_BASE_URL="${TRANSLATION_AGENT_STATUS_BASE_URL:-http://$PUBLIC_HOST:$LIVEKIT_AGENT_PORT}"
VOICE_AGENT_STATUS_URL="${VOICE_AGENT_STATUS_URL:-http://$PUBLIC_HOST:$VOICE_AGENT_PORT/}"
API_HEALTH_URL="${API_HEALTH_URL:-http://$INTERNAL_SERVICE_HOST:$API_PORT/health}"
GATEWAY_HEALTH_URL="${GATEWAY_HEALTH_URL:-http://$INTERNAL_SERVICE_HOST:$REALTIME_PORT/health}"
TRANSLATION_AGENT_HEALTH_URL="${TRANSLATION_AGENT_HEALTH_URL:-http://$INTERNAL_SERVICE_HOST:$LIVEKIT_AGENT_PORT/worker}"
VOICE_AGENT_HEALTH_URL="${VOICE_AGENT_HEALTH_URL:-http://$INTERNAL_SERVICE_HOST:$VOICE_AGENT_PORT/}"
SRT_INGRESS_HEALTH_URL="${SRT_INGRESS_HEALTH_URL:-$SRT_INGRESS_BRIDGE_BASE_URL/health}"
TAILSCALE_SERVE_API_TARGET="${TAILSCALE_SERVE_API_TARGET:-http://$INTERNAL_SERVICE_HOST:$API_PORT}"
TAILSCALE_SERVE_RTC_TARGET="${TAILSCALE_SERVE_RTC_TARGET:-http://$INTERNAL_SERVICE_HOST:7880/rtc}"
TAILSCALE_SERVE_TWIRP_TARGET="${TAILSCALE_SERVE_TWIRP_TARGET:-http://$INTERNAL_SERVICE_HOST:7880/twirp}"
MODE="${1:-deploy}"
IMAGE_TAG="${AI_PHONE_IMAGE_TAG:-$(git -C "$ROOT_DIR" rev-parse --short HEAD)}"
CALL_FULL_DUPLEX_ENABLED="${CALL_FULL_DUPLEX_ENABLED:-false}"
AI_PHONE_COMPOSE_PROFILES="${AI_PHONE_COMPOSE_PROFILES:-}"
AGENT_STABILITY_WINDOW_SECONDS="${AGENT_STABILITY_WINDOW_SECONDS:-30}"
AGENT_STABILITY_TIMEOUT_SECONDS="${AGENT_STABILITY_TIMEOUT_SECONDS:-180}"
APP_HEALTH_STABILITY_WINDOW_SECONDS="${APP_HEALTH_STABILITY_WINDOW_SECONDS:-10}"
FAST_START_STABILITY_WINDOW_SECONDS="${FAST_START_STABILITY_WINDOW_SECONDS:-5}"
WUJIE_AI_APP_CONTAINER_NAME="${WUJIE_AI_APP_CONTAINER_NAME:-ai-phone-wujie-ai}"
WUJIE_AI_AGENT_CALL_WORKER_ENABLED="${WUJIE_AI_AGENT_CALL_WORKER_ENABLED:-false}"
WUJIE_AI_AIR_DEVICE_GATEWAY_ENABLED="${WUJIE_AI_AIR_DEVICE_GATEWAY_ENABLED:-false}"
WUJIE_AI_VOICE_AGENT_ENABLED=false
WUJIE_AI_SRT_INGRESS_ENABLED=false
if [[ ",$AI_PHONE_COMPOSE_PROFILES," == *",voice-agent,"* ]]; then
  WUJIE_AI_VOICE_AGENT_ENABLED=true
  WUJIE_AI_AGENT_CALL_WORKER_ENABLED=true
fi
if [[ ",$AI_PHONE_COMPOSE_PROFILES," == *",air-device-gateway,"* ]]; then
  WUJIE_AI_AIR_DEVICE_GATEWAY_ENABLED=true
fi
if [[ ",$AI_PHONE_COMPOSE_PROFILES," == *",srt-ingress,"* ]]; then
  WUJIE_AI_SRT_INGRESS_ENABLED=true
fi

case "$MODE" in
  sync|deploy|start|status) ;;
  *) echo "Usage: $0 [sync|deploy|start|status]" >&2; exit 2 ;;
esac

if [[ "$MODE" == "start" && -z "${AI_PHONE_IMAGE_TAG:-}" ]]; then
  IMAGE_TAG="$(ssh "$REMOTE_HOST" \
    "if test -s '$REMOTE_RUNTIME/ai-phone-image-tag'; then \
       cat '$REMOTE_RUNTIME/ai-phone-image-tag'; \
     else \
       docker inspect -f '{{.Config.Image}}' '$WUJIE_AI_APP_CONTAINER_NAME' 2>/dev/null | \
         sed 's#^ai-phone-server:##'; \
     fi")"
  for key in \
    WUJIE_AI_AGENT_CALL_WORKER_ENABLED \
    WUJIE_AI_VOICE_AGENT_ENABLED \
    WUJIE_AI_AIR_DEVICE_GATEWAY_ENABLED \
    WUJIE_AI_SRT_INGRESS_ENABLED; do
    value="$(ssh "$REMOTE_HOST" \
      "docker inspect '$WUJIE_AI_APP_CONTAINER_NAME' --format '{{range .Config.Env}}{{println .}}{{end}}' \
       2>/dev/null | awk -F= -v key='$key' '\$1 == key {print \$2; exit}'")"
    [[ "$value" == "true" || "$value" == "false" ]] || {
      echo "Cannot recover $key from the existing Wujie AI container" >&2
      exit 2
    }
    case "$key" in
      WUJIE_AI_AGENT_CALL_WORKER_ENABLED) WUJIE_AI_AGENT_CALL_WORKER_ENABLED="$value" ;;
      WUJIE_AI_VOICE_AGENT_ENABLED) WUJIE_AI_VOICE_AGENT_ENABLED="$value" ;;
      WUJIE_AI_AIR_DEVICE_GATEWAY_ENABLED) WUJIE_AI_AIR_DEVICE_GATEWAY_ENABLED="$value" ;;
      WUJIE_AI_SRT_INGRESS_ENABLED) WUJIE_AI_SRT_INGRESS_ENABLED="$value" ;;
    esac
  done
fi

[[ "$IMAGE_TAG" =~ ^[A-Za-z0-9_.-]+$ ]] || {
  echo "AI_PHONE_IMAGE_TAG contains unsafe characters" >&2
  exit 2
}

for value in \
  "$PUBLIC_HOST" "$INTERNAL_SERVICE_HOST" "$API_BIND_HOST" \
  "$REALTIME_BIND_HOST" "$LIVEKIT_AGENT_BIND_HOST" \
  "$VOICE_AGENT_BIND_HOST" "$SRT_INGRESS_BIND_HOST" \
  "$TRANSLATION_WORKER_AUDIO_FRAME_SINK_HOST" \
  "$API_TRUST_PROXY_ADDRESSES" "$REALTIME_TRUST_PROXY_ADDRESSES" \
  "$REALTIME_ALLOWED_HOSTS" "$REALTIME_ALLOW_NON_BROWSER_CLIENTS_WITHOUT_ORIGIN" \
  "$CALL_PUBLIC_BASE_URL" "$CALL_LIVEKIT_URL" \
  "$API_BASE_URL" "$REALTIME_WS_ENDPOINT" "$PUBLIC_RATE_LIMIT_REDIS_URL" \
  "$SRT_INGRESS_BRIDGE_BASE_URL" "$ASR_HTTP_ENDPOINT" \
  "$ASR_HTTP_FLUSH_ENDPOINT" "$ASR_STREAM_ENDPOINT" "$ASR_HTTP_HEALTH_URL" \
  "$SPEAKER_HTTP_BASE_URL" "$VOICE_IDENTITY_HTTP_BASE_URL" \
  "$TRANSLATION_BASE_URL" "$TTS_HTTP_ENDPOINT" "$TTS_STREAM_ENDPOINT" \
  "$TTS_WARMUP_ENDPOINT" "$TTS_READINESS_URL" "$LLM_BASE_URL" \
  "$LIVEKIT_WORKER_URL" "$API_STATUS_URL" "$GATEWAY_STATUS_URL" \
  "$TRANSLATION_AGENT_STATUS_BASE_URL" "$VOICE_AGENT_STATUS_URL" \
  "$API_HEALTH_URL" "$GATEWAY_HEALTH_URL" \
  "$TRANSLATION_AGENT_HEALTH_URL" "$VOICE_AGENT_HEALTH_URL" \
  "$SRT_INGRESS_HEALTH_URL" \
  "$TAILSCALE_SERVE_API_TARGET" "$TAILSCALE_SERVE_RTC_TARGET" \
  "$TAILSCALE_SERVE_TWIRP_TARGET"; do
  [[ -n "$value" && "$value" != *"'"* && "$value" != *$'\n'* ]] || {
    echo "Server endpoint configuration contains an unsafe value" >&2
    exit 2
  }
done

for port in "$API_PORT" "$REALTIME_PORT" "$LIVEKIT_AGENT_PORT" \
  "$VOICE_AGENT_PORT" "$SRT_INGRESS_PORT"; do
  [[ "$port" =~ ^[0-9]+$ ]] && (( 10#$port >= 1 && 10#$port <= 65535 )) || {
    echo "Server port configuration must be an integer between 1 and 65535" >&2
    exit 2
  }
done

if [[ "$MODE" == "sync" || "$MODE" == "deploy" ]]; then
  npm --prefix "$ROOT_DIR" run check:source-build -- --json
fi

remote_compose() {
  ssh "$REMOTE_HOST" \
    "AI_PHONE_ENV_FILE='$REMOTE_RUNTIME/server.env' \
     AI_PHONE_DATA_DIR='$REMOTE_RUNTIME/data' \
     AIR_GATEWAY_STATE_DIR='$REMOTE_RUNTIME/data/gateway-state' \
     AIR_GATEWAY_HOST_DEV_DIR='/dev' \
     AIR_GATEWAY_DEVICE_GROUP='dialout' \
     AI_PHONE_IMAGE_TAG='$IMAGE_TAG' \
     WUJIE_AI_AGENT_CALL_WORKER_ENABLED='$WUJIE_AI_AGENT_CALL_WORKER_ENABLED' \
     WUJIE_AI_AIR_DEVICE_GATEWAY_ENABLED='$WUJIE_AI_AIR_DEVICE_GATEWAY_ENABLED' \
     WUJIE_AI_VOICE_AGENT_ENABLED='$WUJIE_AI_VOICE_AGENT_ENABLED' \
     WUJIE_AI_SRT_INGRESS_ENABLED='$WUJIE_AI_SRT_INGRESS_ENABLED' \
     COMPOSE_PROFILES='$AI_PHONE_COMPOSE_PROFILES' \
     docker compose -p ai-phone -f '$REMOTE_SOURCE/infra/ai-phone-server/docker-compose.yaml' $*"
}

postgres_startup_preflight() {
  local storage_driver
  storage_driver="$(ssh "$REMOTE_HOST" \
    "awk -F= '/^API_STORAGE_DRIVER=/{value=substr(\$0,index(\$0,\"=\")+1)} END{print value}' \
     '$REMOTE_RUNTIME/server.env'")"
  [[ "$storage_driver" == "postgres" ]] || return 0
  echo "Checking PostgreSQL primary startup admission before container replacement"
  remote_compose \
    "run --rm --no-deps wujie-ai node services/api-server/dist/infrastructure/storage/postgres-admin.js startup-check"
}

production_env_preflight() {
  [[ "$AI_PHONE_DEPLOY_PROFILE" == "production" ]] || return 0
  [[ "$REALTIME_WS_ENDPOINT" == wss://* ]] || {
    echo "Production profile requires an explicit REALTIME_WS_ENDPOINT=wss://..." >&2
    return 2
  }
  ssh "$REMOTE_HOST" "ENV_FILE='$REMOTE_RUNTIME/server.env' bash -s" <<'REMOTE'
set -euo pipefail
test -s "$ENV_FILE" || {
  echo "Production profile requires an existing server.env; refusing to generate a test env" >&2
  exit 2
}
get_env() {
  local key="$1"
  awk -F= -v key="$key" '$1 == key { value=substr($0, index($0, "=")+1) } END { print value }' "$ENV_FILE"
}
require_value() {
  local key="$1" expected="$2" actual
  actual="$(get_env "$key")"
  [[ "$actual" == "$expected" ]] || {
    echo "Production profile requires $key=$expected (actual: ${actual:-<missing>})" >&2
    exit 2
  }
}
require_nonempty() {
  local key="$1" actual
  actual="$(get_env "$key")"
  [[ -n "$actual" && "$actual" != *replace* && "$actual" != *example* ]] || {
    echo "Production profile requires configured $key" >&2
    exit 2
  }
}
require_value NODE_ENV production
require_value API_TEST_AUTO_ACCOUNT false
require_value AUTH_DEBUG_OTP false
require_value SMS_PROVIDER http
require_value API_STORAGE_DRIVER postgres
require_value POSTGRES_PRIMARY_ENABLED true
require_value REALTIME_ALLOW_QUERY_TOKEN false
require_value PUBLIC_RATE_LIMIT_PROVIDER redis
for key in SMS_HTTP_ENDPOINT SMS_HTTP_API_KEY SMS_HTTP_TEMPLATE_ID \
  POSTGRES_URL REALTIME_WS_ENDPOINT API_CORS_ALLOWED_ORIGINS; do
  require_nonempty "$key"
done
for key in AUTH_TEST_PHONE AUTH_TEST_CODE; do
  if grep -q "^${key}=" "$ENV_FILE"; then
    echo "Production profile forbids $key in server.env" >&2
    exit 2
  fi
done
for key in API_BIND_HOST REALTIME_BIND_HOST LIVEKIT_AGENT_BIND_HOST \
  VOICE_AGENT_BIND_HOST TRANSLATION_WORKER_AUDIO_FRAME_SINK_HOST; do
  actual="$(get_env "$key")"
  [[ "$actual" == 127.0.0.1 || "$actual" == ::1 ]] || {
    echo "Production profile requires $key to bind loopback (actual: ${actual:-<missing>})" >&2
    exit 2
  }
done
REMOTE
}

production_env_preflight

wait_for_wujie_container_health() {
  local stable_seconds=0 previous_restarts="" snapshot
  local running health restarts poll_seconds=2 elapsed=0
  while (( elapsed < AGENT_STABILITY_TIMEOUT_SECONDS )); do
    snapshot="$(ssh "$REMOTE_HOST" \
      "docker inspect '$WUJIE_AI_APP_CONTAINER_NAME' \
       --format '{{.State.Running}}|{{if .State.Health}}{{.State.Health.Status}}{{else}}missing{{end}}|{{.RestartCount}}' \
       2>/dev/null || true" 2>/dev/null || true)"
    IFS='|' read -r running health restarts <<<"$snapshot"
    if [[ "$running" == "true" && "$health" == "healthy" ]]; then
      if [[ -n "$previous_restarts" && "$restarts" == "$previous_restarts" ]]; then
        stable_seconds=$((stable_seconds + poll_seconds))
      else
        stable_seconds=0
      fi
      previous_restarts="$restarts"
      if (( stable_seconds >= APP_HEALTH_STABILITY_WINDOW_SECONDS )); then
        echo "Wujie AI container healthy for ${stable_seconds}s with restartCount=$restarts"
        return 0
      fi
    else
      stable_seconds=0
      previous_restarts="$restarts"
    fi
    sleep "$poll_seconds"
    elapsed=$((elapsed + poll_seconds))
  done
  echo "Wujie AI container did not satisfy the health stability gate" >&2
  return 1
}

wait_for_translation_agent_stability() {
  local stable_seconds=0 previous_restarts="" snapshot info agent_name tts_ready
  local poll_seconds=2 elapsed=0
  while (( elapsed < AGENT_STABILITY_TIMEOUT_SECONDS )); do
    snapshot="$(ssh "$REMOTE_HOST" \
      "container='$WUJIE_AI_APP_CONTAINER_NAME'; \
       state=\$(docker inspect -f '{{.State.Running}}|{{.RestartCount}}' \"\$container\" 2>/dev/null || true); \
       printf '%s' \"\$state\"" 2>/dev/null || true)"
    tts_ready="$(curl -sS -o /dev/null -w '%{http_code}' --max-time 3 \
      "$TTS_READINESS_URL" 2>/dev/null || true)"
    info="$(curl -fsS --max-time 3 \
      "$TRANSLATION_AGENT_STATUS_BASE_URL/worker" 2>/dev/null || true)"
    agent_name="$(AGENT_INFO="$info" node -e '
      try {
        const body = JSON.parse(process.env.AGENT_INFO || "{}");
        if (typeof body.agent_name === "string") process.stdout.write(body.agent_name);
      } catch {}
    ')"
    IFS='|' read -r running restarts <<<"$snapshot"
    if [[ "$running" == "true" && "$tts_ready" == "200" &&
      "$agent_name" == "translation-runtime" ]]; then
      if [[ -n "$previous_restarts" && "$restarts" == "$previous_restarts" ]]; then
        stable_seconds=$((stable_seconds + poll_seconds))
      else
        stable_seconds=0
      fi
      previous_restarts="$restarts"
      if (( stable_seconds >= AGENT_STABILITY_WINDOW_SECONDS )); then
        echo "Translation Agent stable for ${stable_seconds}s with restartCount=$restarts"
        return 0
      fi
    else
      stable_seconds=0
      previous_restarts="$restarts"
    fi
    sleep "$poll_seconds"
    elapsed=$((elapsed + poll_seconds))
  done
  echo "Translation Agent did not satisfy the stability/readiness gate" >&2
  return 1
}

status() {
  remote_compose "ps"
  local api_health gateway_health
  api_health="$(curl -fsS "$API_STATUS_URL")"
  gateway_health="$(curl -fsS "$GATEWAY_STATUS_URL")"
  curl -fsS "$TRANSLATION_AGENT_STATUS_BASE_URL/" >/dev/null
  local agent_info
  agent_info="$(curl -fsS "$TRANSLATION_AGENT_STATUS_BASE_URL/worker")"
  if [[ ",$AI_PHONE_COMPOSE_PROFILES," == *",voice-agent,"* ]]; then
    curl -fsS "$VOICE_AGENT_STATUS_URL" >/dev/null
  fi
  if [[ ",$AI_PHONE_COMPOSE_PROFILES," == *",srt-ingress,"* ]]; then
    ssh "$REMOTE_HOST" \
      "curl -fsS '$SRT_INGRESS_HEALTH_URL' >/dev/null"
  fi
  EXPECTED_WS="$REALTIME_WS_ENDPOINT" \
  API_HEALTH="$api_health" \
  GATEWAY_HEALTH="$gateway_health" \
  AGENT_INFO="$agent_info" \
    node <<'NODE'
const api = JSON.parse(process.env.API_HEALTH);
const gateway = JSON.parse(process.env.GATEWAY_HEALTH);
const agent = JSON.parse(process.env.AGENT_INFO);
const expected = {
  apiStatus: "ok",
  realtimeWsEndpoint: process.env.EXPECTED_WS,
  gatewayStatus: "ok",
  provider: "hymt2_self_hosted",
  asrProvider: "http",
  speakerProvider: "http",
  sessionEventSink: "api",
  agentName: "translation-runtime",
};
const actual = {
  apiStatus: api.status,
  realtimeWsEndpoint: api.realtimeWsEndpoint,
  gatewayStatus: gateway.status,
  provider: gateway.provider,
  asrProvider: gateway.asrProvider,
  speakerProvider: gateway.speakerProvider,
  sessionEventSink: gateway.sessionEventSink,
  agentName: agent.agent_name,
};
for (const [key, value] of Object.entries(expected)) {
  if (actual[key] !== value) {
    throw new Error(`${key} expected ${value}, got ${actual[key] ?? "missing"}`);
  }
}
if (gateway.releaseReadiness?.status !== "ready") {
  throw new Error("Gateway release readiness is not ready");
}
NODE
  echo "ai phone API/Gateway/Translation Agent ready on $PUBLIC_HOST:$API_PORT/$REALTIME_PORT/$LIVEKIT_AGENT_PORT"
}

if [[ "$MODE" == "status" ]]; then
  wait_for_wujie_container_health
  wait_for_translation_agent_stability
  status
  exit 0
fi

if [[ "$MODE" == "start" ]]; then
  postgres_startup_preflight
  remote_compose 'up -d --no-build --remove-orphans'
  APP_HEALTH_STABILITY_WINDOW_SECONDS="$FAST_START_STABILITY_WINDOW_SECONDS"
  AGENT_STABILITY_WINDOW_SECONDS="$FAST_START_STABILITY_WINDOW_SECONDS"
  wait_for_wujie_container_health
  wait_for_translation_agent_stability
  status
  exit 0
fi

ssh "$REMOTE_HOST" "mkdir -p '$REMOTE_SOURCE' '$REMOTE_RUNTIME/data/voice-references'"
rsync -az --delete \
  --exclude='.git/' \
  --exclude='.env*' \
  --exclude='release/domestic/release.env' \
  --exclude='.cache/' \
  --exclude='.data/' \
  --exclude='apps/' \
  --exclude='data/' \
  --exclude='docs/' \
  --exclude='model-eval/' \
  --exclude='node_modules/' \
  --exclude='outputs/' \
  --exclude='test-apps/' \
  --exclude='test-audio/' \
  --exclude='services/model-services/' \
  "$ROOT_DIR/" "$REMOTE_HOST:$REMOTE_SOURCE/"

if [[ "${MIGRATE_LOCAL_DATA:-false}" == "true" ]]; then
  rsync -az "$ROOT_DIR/services/api-server/.data/" \
    "$REMOTE_HOST:$REMOTE_RUNTIME/data/"
fi

ssh "$REMOTE_HOST" \
  "REMOTE_RUNTIME='$REMOTE_RUNTIME' \
   PUBLIC_HOST='$PUBLIC_HOST' \
   API_BIND_HOST='$API_BIND_HOST' \
   REALTIME_BIND_HOST='$REALTIME_BIND_HOST' \
   LIVEKIT_AGENT_BIND_HOST='$LIVEKIT_AGENT_BIND_HOST' \
   VOICE_AGENT_BIND_HOST='$VOICE_AGENT_BIND_HOST' \
   SRT_INGRESS_BIND_HOST='$SRT_INGRESS_BIND_HOST' \
   TRANSLATION_WORKER_AUDIO_FRAME_SINK_HOST='$TRANSLATION_WORKER_AUDIO_FRAME_SINK_HOST' \
   TRANSLATION_WORKER_AUDIO_FRAME_SIZE_MS='$TRANSLATION_WORKER_AUDIO_FRAME_SIZE_MS' \
   TRANSLATION_WORKER_AUDIO_INGEST_MAX_FRAMES='$TRANSLATION_WORKER_AUDIO_INGEST_MAX_FRAMES' \
   API_TRUST_PROXY_ADDRESSES='$API_TRUST_PROXY_ADDRESSES' \
   REALTIME_TRUST_PROXY_ADDRESSES='$REALTIME_TRUST_PROXY_ADDRESSES' \
   REALTIME_ALLOWED_HOSTS='$REALTIME_ALLOWED_HOSTS' \
   REALTIME_ALLOW_NON_BROWSER_CLIENTS_WITHOUT_ORIGIN='$REALTIME_ALLOW_NON_BROWSER_CLIENTS_WITHOUT_ORIGIN' \
   API_PORT='$API_PORT' \
   REALTIME_PORT='$REALTIME_PORT' \
   LIVEKIT_AGENT_PORT='$LIVEKIT_AGENT_PORT' \
   VOICE_AGENT_PORT='$VOICE_AGENT_PORT' \
   SRT_INGRESS_PORT='$SRT_INGRESS_PORT' \
   CALL_PUBLIC_BASE_URL='$CALL_PUBLIC_BASE_URL' \
   CALL_LIVEKIT_URL='$CALL_LIVEKIT_URL' \
   API_BASE_URL='$API_BASE_URL' \
   REALTIME_WS_ENDPOINT='$REALTIME_WS_ENDPOINT' \
   PUBLIC_RATE_LIMIT_REDIS_URL='$PUBLIC_RATE_LIMIT_REDIS_URL' \
   SRT_INGRESS_BRIDGE_BASE_URL='$SRT_INGRESS_BRIDGE_BASE_URL' \
   ASR_HTTP_ENDPOINT='$ASR_HTTP_ENDPOINT' \
   ASR_HTTP_FLUSH_ENDPOINT='$ASR_HTTP_FLUSH_ENDPOINT' \
   ASR_STREAM_ENDPOINT='$ASR_STREAM_ENDPOINT' \
   ASR_HTTP_HEALTH_URL='$ASR_HTTP_HEALTH_URL' \
   SPEAKER_HTTP_BASE_URL='$SPEAKER_HTTP_BASE_URL' \
   VOICE_IDENTITY_HTTP_BASE_URL='$VOICE_IDENTITY_HTTP_BASE_URL' \
   TRANSLATION_BASE_URL='$TRANSLATION_BASE_URL' \
   TTS_HTTP_ENDPOINT='$TTS_HTTP_ENDPOINT' \
   TTS_STREAM_ENDPOINT='$TTS_STREAM_ENDPOINT' \
   TTS_WARMUP_ENDPOINT='$TTS_WARMUP_ENDPOINT' \
   LLM_BASE_URL='$LLM_BASE_URL' \
   LIVEKIT_WORKER_URL='$LIVEKIT_WORKER_URL' \
   API_HEALTH_URL='$API_HEALTH_URL' \
   GATEWAY_HEALTH_URL='$GATEWAY_HEALTH_URL' \
   TRANSLATION_AGENT_HEALTH_URL='$TRANSLATION_AGENT_HEALTH_URL' \
   VOICE_AGENT_HEALTH_URL='$VOICE_AGENT_HEALTH_URL' \
   SRT_INGRESS_HEALTH_URL='$SRT_INGRESS_HEALTH_URL' bash -s" <<'REMOTE'
set -euo pipefail
env_file="$REMOTE_RUNTIME/server.env"
if [[ -f "$env_file" ]]; then
  if ! grep -q '^PUBLIC_RATE_LIMIT_PROVIDER=' "$env_file"; then
    umask 077
    public_rate_limit_secret="$(openssl rand -hex 32)"
    cat >>"$env_file" <<EOF
API_BODY_LIMIT_BYTES=16777216
API_CORS_ALLOWED_ORIGINS=$CALL_PUBLIC_BASE_URL
API_TRUST_PROXY_ADDRESSES=$API_TRUST_PROXY_ADDRESSES
PUBLIC_RATE_LIMIT_PROVIDER=redis
PUBLIC_RATE_LIMIT_REDIS_URL=$PUBLIC_RATE_LIMIT_REDIS_URL
PUBLIC_RATE_LIMIT_KEY_PREFIX=wujie:public
PUBLIC_RATE_LIMIT_KEY_SECRET=$public_rate_limit_secret
PUBLIC_RATE_LIMIT_CONNECT_TIMEOUT_MS=1500
REALTIME_ALLOWED_ORIGINS=$CALL_PUBLIC_BASE_URL
REALTIME_ALLOWED_HOSTS=$REALTIME_ALLOWED_HOSTS
REALTIME_ALLOW_NON_BROWSER_CLIENTS_WITHOUT_ORIGIN=$REALTIME_ALLOW_NON_BROWSER_CLIENTS_WITHOUT_ORIGIN
REALTIME_TRUST_PROXY_ADDRESSES=$REALTIME_TRUST_PROXY_ADDRESSES
REALTIME_MAX_PAYLOAD_BYTES=65536
REALTIME_MAX_CONNECTIONS=512
REALTIME_MAX_CONNECTIONS_PER_IP=8
REALTIME_MAX_SESSIONS=256
REALTIME_MAX_MESSAGES_PER_SECOND=120
REALTIME_MAX_AUDIO_FRAMES_PER_SECOND=75
REALTIME_MAX_PENDING_AUDIO_MS=6000
REALTIME_MAX_PENDING_CONTROL_EVENTS=32
REALTIME_MAX_PENDING_TTS_OUTPUTS=32
REALTIME_HANDSHAKE_RATE_LIMIT_PER_MINUTE=30
EOF
    chmod 600 "$env_file"
  fi
  exit 0
fi

set -a
source /data/models/translation-model-eval/services/asr-service-qwen3/.env
source /data/models/translation-model-eval/services/translation-service/.env
source /data/models/translation-model-eval/services/speaker-service/.env
source /data/models/translation-model-eval/services/tts-service/.env
source /home/beelink/livekit-qkxy/release.env.snippet
set +a
umask 077
token_secret="$(openssl rand -hex 32)"
internal_secret="$(openssl rand -hex 32)"
dispatch_secret="$(openssl rand -hex 32)"
voice_dispatch_secret="$(openssl rand -hex 32)"
srt_bridge_secret="$(openssl rand -hex 32)"
otp_secret="$(openssl rand -hex 32)"
public_rate_limit_secret="$(openssl rand -hex 32)"
cat >"$env_file" <<EOF
NODE_ENV=development
API_BIND_HOST=$API_BIND_HOST
API_PORT=$API_PORT
REALTIME_BIND_HOST=$REALTIME_BIND_HOST
REALTIME_PORT=$REALTIME_PORT
API_BODY_LIMIT_BYTES=16777216
API_CORS_ALLOWED_ORIGINS=$CALL_PUBLIC_BASE_URL
API_TRUST_PROXY_ADDRESSES=$API_TRUST_PROXY_ADDRESSES
PUBLIC_RATE_LIMIT_PROVIDER=redis
PUBLIC_RATE_LIMIT_REDIS_URL=$PUBLIC_RATE_LIMIT_REDIS_URL
PUBLIC_RATE_LIMIT_KEY_PREFIX=wujie:public
PUBLIC_RATE_LIMIT_KEY_SECRET=$public_rate_limit_secret
PUBLIC_RATE_LIMIT_CONNECT_TIMEOUT_MS=1500
API_BASE_URL=$API_BASE_URL
API_HEALTH_URL=$API_HEALTH_URL
REALTIME_WS_ENDPOINT=$REALTIME_WS_ENDPOINT
GATEWAY_HEALTH_URL=$GATEWAY_HEALTH_URL
PUBLIC_CALL_BASE_URL=$CALL_PUBLIC_BASE_URL
API_STORAGE_DRIVER=sqlite
API_DATA_FILE=/data/ai-phone/api-store.json
API_SQLITE_FILE=/data/ai-phone/api-store.sqlite
VOICE_PROFILE_REFERENCE_DIR=/data/ai-phone/voice-references
REALTIME_TOKEN_SECRET=$token_secret
REALTIME_ALLOW_QUERY_TOKEN=false
REALTIME_ALLOWED_ORIGINS=$CALL_PUBLIC_BASE_URL
REALTIME_ALLOWED_HOSTS=$REALTIME_ALLOWED_HOSTS
REALTIME_ALLOW_NON_BROWSER_CLIENTS_WITHOUT_ORIGIN=$REALTIME_ALLOW_NON_BROWSER_CLIENTS_WITHOUT_ORIGIN
REALTIME_TRUST_PROXY_ADDRESSES=$REALTIME_TRUST_PROXY_ADDRESSES
REALTIME_MAX_PAYLOAD_BYTES=65536
REALTIME_MAX_CONNECTIONS=512
REALTIME_MAX_CONNECTIONS_PER_IP=8
REALTIME_MAX_SESSIONS=256
REALTIME_MAX_MESSAGES_PER_SECOND=120
REALTIME_MAX_AUDIO_FRAMES_PER_SECOND=75
REALTIME_MAX_PENDING_AUDIO_MS=6000
REALTIME_MAX_PENDING_CONTROL_EVENTS=32
REALTIME_MAX_PENDING_TTS_OUTPUTS=32
REALTIME_HANDSHAKE_RATE_LIMIT_PER_MINUTE=30
INTERNAL_API_SECRET=$internal_secret
TRANSLATION_WORKER_RUNTIME_PROVIDER=livekit_dispatch
TRANSLATION_WORKER_AUDIO_FRAME_SINK_HOST=$TRANSLATION_WORKER_AUDIO_FRAME_SINK_HOST
TRANSLATION_WORKER_AUDIO_FRAME_SIZE_MS=$TRANSLATION_WORKER_AUDIO_FRAME_SIZE_MS
TRANSLATION_WORKER_AUDIO_INGEST_MAX_FRAMES=$TRANSLATION_WORKER_AUDIO_INGEST_MAX_FRAMES
LIVEKIT_DISPATCH_TICKET_SECRET=$dispatch_secret
LIVEKIT_TRANSLATION_AGENT_NAME=translation-runtime
TRANSLATION_AGENT_HEALTH_URL=$TRANSLATION_AGENT_HEALTH_URL
LIVEKIT_DISPATCH_MAX_ACTIVE_JOBS=4
LIVEKIT_DISPATCH_LEASE_SECONDS=45
LIVEKIT_DISPATCH_HEARTBEAT_SECONDS=15
LIVEKIT_DISPATCH_READY_TIMEOUT_SECONDS=20
LIVEKIT_DISPATCH_REQUEST_TIMEOUT_SECONDS=10
LIVEKIT_DISPATCH_MAX_METADATA_BYTES=2048
LIVEKIT_AGENT_MAX_JOBS_PER_NODE=4
LIVEKIT_AGENT_IDLE_PROCESSES=2
LIVEKIT_AGENT_DRAIN_TIMEOUT_SECONDS=60
LIVEKIT_AGENT_SHUTDOWN_TIMEOUT_SECONDS=30
LIVEKIT_AGENT_INITIALIZE_TIMEOUT_SECONDS=20
LIVEKIT_AGENT_JOB_MEMORY_WARN_MB=768
LIVEKIT_AGENT_JOB_MEMORY_LIMIT_MB=1024
LIVEKIT_AGENT_BIND_HOST=$LIVEKIT_AGENT_BIND_HOST
LIVEKIT_AGENT_PORT=$LIVEKIT_AGENT_PORT
AGENT_CALL_WORKER_ENABLED=false
AGENT_CALL_WORKER_ID=
AGENT_CALL_PROVIDER_ADAPTER=
AGENT_CALL_WORKER_LEASE_SECONDS=45
AGENT_CALL_RECONCILIATION_TIMEOUT_SECONDS=7200
PSTN_PROVIDER_IDEMPOTENCY_GUARANTEED=false
VOICE_AGENT_ENABLED=false
VOICE_AGENT_ASSIST_ENABLED=false
VOICE_AGENT_AUTONOMOUS_ENABLED=false
VOICE_AGENT_AUTONOMOUS_USER_IDS=
VOICE_AGENT_AUTONOMOUS_SCENARIOS=booking,customer_support,business_inquiry
VOICE_AGENT_POLICY_VERSION=voice-agent-v1
VOICE_AGENT_RUNTIME_PROVIDER=disabled
LIVEKIT_VOICE_AGENT_NAME=voice-agent-runtime
VOICE_AGENT_HEALTH_URL=$VOICE_AGENT_HEALTH_URL
VOICE_AGENT_DISPATCH_TICKET_SECRET=$voice_dispatch_secret
VOICE_AGENT_DISPATCH_MAX_ACTIVE_JOBS=2
VOICE_AGENT_DISPATCH_LEASE_SECONDS=45
VOICE_AGENT_DISPATCH_HEARTBEAT_SECONDS=15
VOICE_AGENT_DISPATCH_READY_TIMEOUT_SECONDS=25
VOICE_AGENT_DISPATCH_REQUEST_TIMEOUT_SECONDS=10
VOICE_AGENT_MAX_JOBS_PER_NODE=2
VOICE_AGENT_IDLE_PROCESSES=1
VOICE_AGENT_DRAIN_TIMEOUT_SECONDS=90
VOICE_AGENT_SHUTDOWN_TIMEOUT_SECONDS=45
VOICE_AGENT_INITIALIZE_TIMEOUT_SECONDS=30
VOICE_AGENT_JOB_MEMORY_WARN_MB=768
VOICE_AGENT_JOB_MEMORY_LIMIT_MB=1024
VOICE_AGENT_BIND_HOST=$VOICE_AGENT_BIND_HOST
VOICE_AGENT_PORT=$VOICE_AGENT_PORT
VOICE_AGENT_API_TIMEOUT_MS=10000
VOICE_AGENT_RESPONSE_START_TIMEOUT_MS=12000
VOICE_AGENT_MAX_PENDING_AUDIO_MS=6000
VOICE_AGENT_MAX_PENDING_AUDIO_CHUNKS=300
VOICE_AGENT_BACKGROUND_WORK_ENABLED=false
VOICE_AGENT_WORK_RUNNER_ENABLED=false
VOICE_AGENT_DELIVERY_COORDINATOR_ENABLED=false
VOICE_AGENT_OWNERSHIP_ENABLED=false
VOICE_AGENT_AUDIO_REALTIME_SHADOW_ENABLED=false
VOICE_AGENT_AUDIO_REALTIME_SHADOW_ENDPOINT=
VOICE_AGENT_AUDIO_REALTIME_SHADOW_API_KEY=
VOICE_AGENT_AUDIO_REALTIME_SHADOW_MODEL=qwen-audio-3.0-realtime-flash
VOICE_AGENT_AUDIO_REALTIME_SHADOW_MAX_BUFFERED_MS=2000
VOICE_AGENT_AUDIO_REALTIME_SHADOW_MAX_BUFFERED_CHUNKS=20
VOICE_AGENT_AUDIO_REALTIME_SHADOW_CONNECT_TIMEOUT_MS=5000
AGENT_DELIVERY_COORDINATOR_OWNER=agent-delivery-beelink
AGENT_DELIVERY_COORDINATOR_POLL_MS=1000
AGENT_DELIVERY_COORDINATOR_LEASE_SECONDS=30
AGENT_DELIVERY_COORDINATOR_CONCURRENCY=2
VOICE_AGENT_AMD_NO_SPEECH_TIMEOUT_MS=12000
VOICE_AGENT_AMD_DETECTION_TIMEOUT_MS=30000
VOICE_AGENT_VOICEMAIL_ENABLED=false
VOICE_AGENT_MAX_SESSION_SECONDS=7200
VOICE_AGENT_HANDOFF_TIMEOUT_SECONDS=120
VOICE_AGENT_OPERATOR_CONSULT_ENABLED=false
VOICE_AGENT_OPERATOR_CONSULT_TTL_SECONDS=180
VOICE_AGENT_OPERATOR_CONSULT_MAX_ATTEMPTS=3
LIVEKIT_EGRESS_ENABLED=false
LIVEKIT_EGRESS_REQUEST_TIMEOUT_SECONDS=10
LIVEKIT_EGRESS_OBJECT_PREFIX=recordings
LIVEKIT_EGRESS_MAX_RETENTION_DAYS=30
LIVEKIT_EGRESS_ARTIFACT_WORKER_ENABLED=false
LIVEKIT_INGRESS_ENABLED=false
LIVEKIT_INGRESS_REQUEST_TIMEOUT_SECONDS=10
LIVEKIT_INGRESS_MAX_ACTIVE_PER_SESSION=1
LIVEKIT_INGRESS_MAX_ACTIVE_TOTAL=8
LIVEKIT_INGRESS_POLICY_VERSION=external-media-v1
LIVEKIT_INGRESS_URL_INPUT_ENABLED=false
LIVEKIT_INGRESS_PULL_URL_HOSTS=
LIVEKIT_INGRESS_PULL_NETWORK_POLICY_ENFORCED=false
LIVEKIT_INGRESS_SOURCE_PREFLIGHT_TIMEOUT_MS=3000
LIVEKIT_INGRESS_SOURCE_MAX_REDIRECTS=2
LIVEKIT_INGRESS_SRT_ENABLED=false
SRT_INGRESS_BRIDGE_BASE_URL=$SRT_INGRESS_BRIDGE_BASE_URL
SRT_INGRESS_HEALTH_URL=$SRT_INGRESS_HEALTH_URL
SRT_INGRESS_BRIDGE_API_KEY=$srt_bridge_secret
SRT_INGRESS_PUBLIC_HOST=$PUBLIC_HOST
SRT_INGRESS_BIND_HOST=$SRT_INGRESS_BIND_HOST
SRT_INGRESS_PORT=$SRT_INGRESS_PORT
SRT_INGRESS_PORT_MIN=10080
SRT_INGRESS_PORT_MAX=10179
SRT_INGRESS_MAX_JOBS=4
SRT_INGRESS_LATENCY_MS=200
SRT_INGRESS_MAX_DURATION_SECONDS=7200
SRT_INGRESS_SHUTDOWN_GRACE_MS=10000
SRT_INGRESS_RTMP_ALLOWED_HOSTS=
SRT_INGRESS_FFMPEG_PATH=/usr/bin/ffmpeg
AUTH_OTP_SECRET=$otp_secret
API_TEST_AUTO_ACCOUNT=true
AUTH_TEST_PHONE=13800000000
AUTH_TEST_CODE=123456
REGION_EDITION=domestic
DATA_REGION=cn
CALL_PROVIDER_POLICY=call_link_only
COMPLIANCE_PROFILE=pipl
ACTIVE_PLAN_CODE=premium
SPEECH_PIPELINE_MODE=cascade
REALTIME_PROVIDER=hymt2_self_hosted
SESSION_EVENT_SINK=api
ASR_PROVIDER=http
ASR_HTTP_ENDPOINT=$ASR_HTTP_ENDPOINT
ASR_HTTP_FLUSH_ENDPOINT=$ASR_HTTP_FLUSH_ENDPOINT
ASR_STREAM_ENDPOINT=$ASR_STREAM_ENDPOINT
ASR_STREAM_FALLBACK_TO_HTTP=true
ASR_HTTP_HEALTH_URL=$ASR_HTTP_HEALTH_URL
ASR_HTTP_API_KEY=$ASR_SERVICE_API_KEY
ASR_HTTP_TIMEOUT_MS=120000
SPEAKER_PROVIDER=http
SPEAKER_HTTP_BASE_URL=$SPEAKER_HTTP_BASE_URL
SPEAKER_HTTP_API_KEY=$SPEAKER_SERVICE_API_KEY
SPEAKER_HTTP_TIMEOUT_MS=2000
VOICE_IDENTITY_HTTP_BASE_URL=$VOICE_IDENTITY_HTTP_BASE_URL
VOICE_IDENTITY_HTTP_TIMEOUT_MS=30000
TRANSLATION_BASE_URL=$TRANSLATION_BASE_URL
TRANSLATION_MODEL=tencent/Hy-MT2-1.8B
TRANSLATION_API_KEY=$TRANSLATION_SERVICE_API_KEY
TRANSLATION_TIMEOUT_MS=20000
TRANSLATION_MAX_TOKENS=512
TRANSLATION_STREAMING_ENABLED=true
TTS_HTTP_ENDPOINT=$TTS_HTTP_ENDPOINT
TTS_STREAM_ENDPOINT=$TTS_STREAM_ENDPOINT
TTS_WARMUP_ENDPOINT=$TTS_WARMUP_ENDPOINT
TTS_WARMUP_MAX_MS=15000
TTS_HTTP_API_KEY=$TTS_SERVICE_API_KEY
TTS_HTTP_TIMEOUT_MS=30000
TTS_AGENT_PREWARM_TIMEOUT_MS=60000
LLM_PROVIDER=openai_compatible
LLM_BASE_URL=$LLM_BASE_URL
LLM_CORRECTION_MODEL=qwen/qwen3.5-9b
LLM_REVIEW_MODEL=qwen/qwen3.5-9b
LLM_REFINEMENT_ENABLED=true
LLM_REVIEW_ENABLED=true
LLM_REASONING_EFFORT=none
LLM_CORRECTION_TIMEOUT_MS=10000
DOMAIN_LEXICON_PACKS=product,business,technology,medical,travel,dining,entertainment
CALL_ROOM_PROVIDER=livekit
LIVEKIT_URL=$CALL_LIVEKIT_URL
LIVEKIT_WORKER_URL=$LIVEKIT_WORKER_URL
LIVEKIT_API_KEY=$LIVEKIT_API_KEY
LIVEKIT_API_SECRET=$LIVEKIT_API_SECRET
CALL_ROOM_TOKEN_TTL_SECONDS=${CALL_ROOM_TOKEN_TTL_SECONDS:-120}
CALL_GUEST_TICKET_TTL_SECONDS=${CALL_GUEST_TICKET_TTL_SECONDS:-300}
CALL_ROOM_MAX_PARTICIPANTS=${CALL_ROOM_MAX_PARTICIPANTS:-3}
CALL_ROOM_MAX_SESSION_SECONDS=${CALL_ROOM_MAX_SESSION_SECONDS:-3600}
CALL_ROOM_EMPTY_TIMEOUT_SECONDS=${CALL_ROOM_EMPTY_TIMEOUT_SECONDS:-300}
CALL_ROOM_MAX_DATA_PACKET_BYTES=${CALL_ROOM_MAX_DATA_PACKET_BYTES:-12288}
CALL_ROOM_MAX_EVENTS_PER_REQUEST=${CALL_ROOM_MAX_EVENTS_PER_REQUEST:-20}
CALL_ROOM_MAX_EVENT_REQUESTS_PER_SECOND=${CALL_ROOM_MAX_EVENT_REQUESTS_PER_SECOND:-40}
CALL_ROOM_MAX_PARTICIPANT_NAME_CHARACTERS=${CALL_ROOM_MAX_PARTICIPANT_NAME_CHARACTERS:-80}
EOF
chmod 600 "$env_file"
REMOTE

ssh "$REMOTE_HOST" \
  "ENV_FILE='$REMOTE_RUNTIME/server.env' \
   PUBLIC_HOST='$PUBLIC_HOST' \
   API_BIND_HOST='$API_BIND_HOST' \
   REALTIME_BIND_HOST='$REALTIME_BIND_HOST' \
   LIVEKIT_AGENT_BIND_HOST='$LIVEKIT_AGENT_BIND_HOST' \
   VOICE_AGENT_BIND_HOST='$VOICE_AGENT_BIND_HOST' \
   SRT_INGRESS_BIND_HOST='$SRT_INGRESS_BIND_HOST' \
   TRANSLATION_WORKER_AUDIO_FRAME_SINK_HOST='$TRANSLATION_WORKER_AUDIO_FRAME_SINK_HOST' \
   TRANSLATION_WORKER_AUDIO_FRAME_SIZE_MS='$TRANSLATION_WORKER_AUDIO_FRAME_SIZE_MS' \
   TRANSLATION_WORKER_AUDIO_INGEST_MAX_FRAMES='$TRANSLATION_WORKER_AUDIO_INGEST_MAX_FRAMES' \
   API_TRUST_PROXY_ADDRESSES='$API_TRUST_PROXY_ADDRESSES' \
   REALTIME_TRUST_PROXY_ADDRESSES='$REALTIME_TRUST_PROXY_ADDRESSES' \
   REALTIME_ALLOWED_HOSTS='$REALTIME_ALLOWED_HOSTS' \
   REALTIME_ALLOW_NON_BROWSER_CLIENTS_WITHOUT_ORIGIN='$REALTIME_ALLOW_NON_BROWSER_CLIENTS_WITHOUT_ORIGIN' \
   API_PORT='$API_PORT' \
   REALTIME_PORT='$REALTIME_PORT' \
   LIVEKIT_AGENT_PORT='$LIVEKIT_AGENT_PORT' \
   VOICE_AGENT_PORT='$VOICE_AGENT_PORT' \
   SRT_INGRESS_PORT='$SRT_INGRESS_PORT' \
   CALL_PUBLIC_BASE_URL='$CALL_PUBLIC_BASE_URL' \
   CALL_LIVEKIT_URL='$CALL_LIVEKIT_URL' \
   API_BASE_URL='$API_BASE_URL' \
   REALTIME_WS_ENDPOINT='$REALTIME_WS_ENDPOINT' \
   PUBLIC_RATE_LIMIT_REDIS_URL='$PUBLIC_RATE_LIMIT_REDIS_URL' \
   SRT_INGRESS_BRIDGE_BASE_URL='$SRT_INGRESS_BRIDGE_BASE_URL' \
   ASR_HTTP_ENDPOINT='$ASR_HTTP_ENDPOINT' \
   ASR_HTTP_FLUSH_ENDPOINT='$ASR_HTTP_FLUSH_ENDPOINT' \
   ASR_STREAM_ENDPOINT='$ASR_STREAM_ENDPOINT' \
   ASR_HTTP_HEALTH_URL='$ASR_HTTP_HEALTH_URL' \
   SPEAKER_HTTP_BASE_URL='$SPEAKER_HTTP_BASE_URL' \
   VOICE_IDENTITY_HTTP_BASE_URL='$VOICE_IDENTITY_HTTP_BASE_URL' \
   TRANSLATION_BASE_URL='$TRANSLATION_BASE_URL' \
   TTS_HTTP_ENDPOINT='$TTS_HTTP_ENDPOINT' \
   TTS_STREAM_ENDPOINT='$TTS_STREAM_ENDPOINT' \
   TTS_WARMUP_ENDPOINT='$TTS_WARMUP_ENDPOINT' \
   LLM_BASE_URL='$LLM_BASE_URL' \
   LIVEKIT_WORKER_URL='$LIVEKIT_WORKER_URL' \
   API_HEALTH_URL='$API_HEALTH_URL' \
   GATEWAY_HEALTH_URL='$GATEWAY_HEALTH_URL' \
   TRANSLATION_AGENT_HEALTH_URL='$TRANSLATION_AGENT_HEALTH_URL' \
   VOICE_AGENT_HEALTH_URL='$VOICE_AGENT_HEALTH_URL' \
   SRT_INGRESS_HEALTH_URL='$SRT_INGRESS_HEALTH_URL' \
   CALL_FULL_DUPLEX_ENABLED='$CALL_FULL_DUPLEX_ENABLED' bash -s" <<'REMOTE'
set -euo pipefail
set_env() {
  local key="$1" value="$2"
  if grep -q "^${key}=" "$ENV_FILE"; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
  else
    printf '%s=%s\n' "$key" "$value" >>"$ENV_FILE"
  fi
}
set_env PUBLIC_CALL_BASE_URL "$CALL_PUBLIC_BASE_URL"
set_env LIVEKIT_URL "$CALL_LIVEKIT_URL"
set_env API_BIND_HOST "$API_BIND_HOST"
set_env API_PORT "$API_PORT"
set_env API_TRUST_PROXY_ADDRESSES "$API_TRUST_PROXY_ADDRESSES"
set_env API_BASE_URL "$API_BASE_URL"
set_env API_HEALTH_URL "$API_HEALTH_URL"
set_env REALTIME_BIND_HOST "$REALTIME_BIND_HOST"
set_env REALTIME_PORT "$REALTIME_PORT"
set_env REALTIME_TRUST_PROXY_ADDRESSES "$REALTIME_TRUST_PROXY_ADDRESSES"
set_env REALTIME_ALLOWED_HOSTS "$REALTIME_ALLOWED_HOSTS"
set_env REALTIME_ALLOW_NON_BROWSER_CLIENTS_WITHOUT_ORIGIN "$REALTIME_ALLOW_NON_BROWSER_CLIENTS_WITHOUT_ORIGIN"
set_env REALTIME_WS_ENDPOINT "$REALTIME_WS_ENDPOINT"
set_env GATEWAY_HEALTH_URL "$GATEWAY_HEALTH_URL"
set_env PUBLIC_RATE_LIMIT_REDIS_URL "$PUBLIC_RATE_LIMIT_REDIS_URL"
set_env LIVEKIT_WORKER_URL "$LIVEKIT_WORKER_URL"
set_env CALL_ROOM_TOKEN_TTL_SECONDS "120"
set_env CALL_FULL_DUPLEX_ENABLED "$CALL_FULL_DUPLEX_ENABLED"
set_env TRANSLATION_WORKER_RUNTIME_PROVIDER "livekit_dispatch"
set_env TRANSLATION_WORKER_AUDIO_FRAME_SINK_HOST "$TRANSLATION_WORKER_AUDIO_FRAME_SINK_HOST"
set_env TRANSLATION_WORKER_AUDIO_FRAME_SIZE_MS "$TRANSLATION_WORKER_AUDIO_FRAME_SIZE_MS"
set_env TRANSLATION_WORKER_AUDIO_INGEST_MAX_FRAMES "$TRANSLATION_WORKER_AUDIO_INGEST_MAX_FRAMES"
set_env LIVEKIT_TRANSLATION_AGENT_NAME "translation-runtime"
set_env LIVEKIT_AGENT_BIND_HOST "$LIVEKIT_AGENT_BIND_HOST"
set_env LIVEKIT_AGENT_PORT "$LIVEKIT_AGENT_PORT"
set_env TRANSLATION_AGENT_HEALTH_URL "$TRANSLATION_AGENT_HEALTH_URL"
if ! grep -q '^LIVEKIT_DISPATCH_TICKET_SECRET=' "$ENV_FILE"; then
  set_env LIVEKIT_DISPATCH_TICKET_SECRET "$(openssl rand -hex 32)"
fi
if ! grep -q '^VOICE_AGENT_DISPATCH_TICKET_SECRET=' "$ENV_FILE"; then
  set_env VOICE_AGENT_DISPATCH_TICKET_SECRET "$(openssl rand -hex 32)"
fi
if ! grep -q '^VOICE_AGENT_RUNTIME_PROVIDER=' "$ENV_FILE"; then
  set_env VOICE_AGENT_RUNTIME_PROVIDER "disabled"
fi
if ! grep -q '^SRT_INGRESS_BRIDGE_API_KEY=' "$ENV_FILE"; then
  set_env SRT_INGRESS_BRIDGE_API_KEY "$(openssl rand -hex 32)"
fi
if ! grep -q '^LIVEKIT_INGRESS_SRT_ENABLED=' "$ENV_FILE"; then
  set_env LIVEKIT_INGRESS_SRT_ENABLED "false"
fi
if ! grep -q '^SRT_INGRESS_RTMP_ALLOWED_HOSTS=' "$ENV_FILE"; then
  set_env SRT_INGRESS_RTMP_ALLOWED_HOSTS ""
fi
set_env SRT_INGRESS_BRIDGE_BASE_URL "$SRT_INGRESS_BRIDGE_BASE_URL"
set_env SRT_INGRESS_PUBLIC_HOST "$PUBLIC_HOST"
set_env SRT_INGRESS_BIND_HOST "$SRT_INGRESS_BIND_HOST"
set_env SRT_INGRESS_PORT "$SRT_INGRESS_PORT"
set_env LIVEKIT_VOICE_AGENT_NAME "voice-agent-runtime"
set_env VOICE_AGENT_BIND_HOST "$VOICE_AGENT_BIND_HOST"
set_env VOICE_AGENT_PORT "$VOICE_AGENT_PORT"
set_env VOICE_AGENT_HEALTH_URL "$VOICE_AGENT_HEALTH_URL"
set_env VOICE_AGENT_RESPONSE_START_TIMEOUT_MS "12000"
set_env VOICE_AGENT_MAX_PENDING_AUDIO_MS "6000"
set_env VOICE_AGENT_MAX_PENDING_AUDIO_CHUNKS "300"
set_env VOICE_AGENT_BACKGROUND_WORK_ENABLED "false"
set_env VOICE_AGENT_WORK_RUNNER_ENABLED "false"
set_env VOICE_AGENT_DELIVERY_COORDINATOR_ENABLED "false"
set_env VOICE_AGENT_OWNERSHIP_ENABLED "false"
if ! grep -q '^VOICE_AGENT_AUDIO_REALTIME_SHADOW_ENABLED=' "$ENV_FILE"; then
  set_env VOICE_AGENT_AUDIO_REALTIME_SHADOW_ENABLED "false"
fi
if ! grep -q '^VOICE_AGENT_AUDIO_REALTIME_SHADOW_ENDPOINT=' "$ENV_FILE"; then
  set_env VOICE_AGENT_AUDIO_REALTIME_SHADOW_ENDPOINT ""
fi
if ! grep -q '^VOICE_AGENT_AUDIO_REALTIME_SHADOW_API_KEY=' "$ENV_FILE"; then
  set_env VOICE_AGENT_AUDIO_REALTIME_SHADOW_API_KEY ""
fi
set_env VOICE_AGENT_AUDIO_REALTIME_SHADOW_MODEL \
  "qwen-audio-3.0-realtime-flash"
set_env VOICE_AGENT_AUDIO_REALTIME_SHADOW_MAX_BUFFERED_MS "2000"
set_env VOICE_AGENT_AUDIO_REALTIME_SHADOW_MAX_BUFFERED_CHUNKS "20"
set_env VOICE_AGENT_AUDIO_REALTIME_SHADOW_CONNECT_TIMEOUT_MS "5000"
set_env AGENT_DELIVERY_COORDINATOR_OWNER "agent-delivery-beelink"
set_env AGENT_DELIVERY_COORDINATOR_POLL_MS "1000"
set_env AGENT_DELIVERY_COORDINATOR_LEASE_SECONDS "30"
set_env AGENT_DELIVERY_COORDINATOR_CONCURRENCY "2"
set_env SRT_INGRESS_HEALTH_URL "$SRT_INGRESS_HEALTH_URL"
set_env CALL_BARGE_IN_MIN_SPEECH_MS "240"
set_env CALL_BARGE_IN_MIN_PROBABILITY "0.5"
set_env CALL_BARGE_IN_COOLDOWN_MS "800"
set_env CALL_BARGE_IN_PRE_ROLL_MS "400"
set_env CALL_ECHO_START_GATE_ENABLED "true"
set_env CALL_ECHO_BARGE_IN_MIN_SPEECH_MS "480"
set_env CALL_ECHO_BARGE_IN_MIN_PROBABILITY "0.72"
set_env CALL_BACKCHANNEL_MAX_SPEECH_MS "360"
set_env PROVIDER_FALLBACK_FAILURE_THRESHOLD "1"
set_env PROVIDER_FALLBACK_COOLDOWN_MS "30000"
set_env CALL_PIPELINE_END_GRACE_MS "1500"
set_env LLM_FALLBACK_COOLDOWN_MS "30000"
set_env LLM_CORRECTION_TIMEOUT_MS "10000"
set_env DOMAIN_LEXICON_PACKS "product,business,technology,medical,travel,dining,entertainment"
set_env ASR_HTTP_ENDPOINT "$ASR_HTTP_ENDPOINT"
set_env ASR_HTTP_FLUSH_ENDPOINT "$ASR_HTTP_FLUSH_ENDPOINT"
set_env ASR_STREAM_ENDPOINT "$ASR_STREAM_ENDPOINT"
set_env ASR_HTTP_HEALTH_URL "$ASR_HTTP_HEALTH_URL"
set_env SPEAKER_HTTP_BASE_URL "$SPEAKER_HTTP_BASE_URL"
set_env VOICE_IDENTITY_HTTP_BASE_URL "$VOICE_IDENTITY_HTTP_BASE_URL"
set_env TRANSLATION_BASE_URL "$TRANSLATION_BASE_URL"
set_env TTS_HTTP_ENDPOINT "$TTS_HTTP_ENDPOINT"
set_env TTS_STREAM_ENDPOINT "$TTS_STREAM_ENDPOINT"
set_env TTS_WARMUP_ENDPOINT "$TTS_WARMUP_ENDPOINT"
set_env LLM_BASE_URL "$LLM_BASE_URL"
set_env VOICE_IDENTITY_HTTP_TIMEOUT_MS "30000"
REMOTE

ssh "$REMOTE_HOST" "set -euo pipefail
tailscale serve --bg --https=443 --set-path=/ '$TAILSCALE_SERVE_API_TARGET'
tailscale serve --bg --https=443 --set-path=/rtc '$TAILSCALE_SERVE_RTC_TARGET'
tailscale serve --bg --https=443 --set-path=/twirp '$TAILSCALE_SERVE_TWIRP_TARGET'"

if [[ "$MODE" == "sync" ]]; then
  echo "Synced ai phone server source to $REMOTE_HOST:$REMOTE_SOURCE"
  exit 0
fi

remote_compose "build"
postgres_startup_preflight

if [[ "${MIGRATE_SQLITE:-false}" == "true" ]]; then
  backup_stamp="$(date -u +%Y%m%dT%H%M%SZ)"
  previous_driver="$(ssh "$REMOTE_HOST" \
    "awk -F= '/^API_STORAGE_DRIVER=/{print \$2}' '$REMOTE_RUNTIME/server.env' | tail -1")"
  remote_compose "stop wujie-ai"
  migration_services_stopped=true
  recover_migration_services() {
    if [[ "$migration_services_stopped" == "true" ]]; then
      remote_compose "start wujie-ai" || true
    fi
  }
  trap recover_migration_services ERR
  ssh "$REMOTE_HOST" \
    "set -euo pipefail; test -s '$REMOTE_RUNTIME/data/api-store.json'; \
     cp --reflink=auto '$REMOTE_RUNTIME/data/api-store.json' \
       '$REMOTE_RUNTIME/data/api-store.json.backup-$backup_stamp'"
  if [[ "$previous_driver" != "sqlite" ]]; then
    ssh "$REMOTE_HOST" \
      "if test -e '$REMOTE_RUNTIME/data/api-store.sqlite'; then \
         mv '$REMOTE_RUNTIME/data/api-store.sqlite' \
           '$REMOTE_RUNTIME/data/api-store.sqlite.pre-migration-$backup_stamp'; \
       fi"
    remote_compose \
      "run --rm --no-deps wujie-ai npm run storage:migrate-json -- \
       /data/ai-phone/api-store.json /data/ai-phone/api-store.sqlite"
  fi
  remote_compose \
    "run --rm --no-deps wujie-ai npm run storage:check -- \
     /data/ai-phone/api-store.sqlite"
  remote_compose \
    "run --rm --no-deps wujie-ai npm run storage:backup -- \
     /data/ai-phone/api-store.sqlite \
     /data/ai-phone/api-store.sqlite.backup-$backup_stamp"
  ssh "$REMOTE_HOST" "ENV_FILE='$REMOTE_RUNTIME/server.env' bash -s" <<'REMOTE'
set -euo pipefail
set_env() {
  local key="$1" value="$2"
  if grep -q "^${key}=" "$ENV_FILE"; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
  else
    printf '%s=%s\n' "$key" "$value" >>"$ENV_FILE"
  fi
}
set_env API_STORAGE_DRIVER sqlite
set_env API_SQLITE_FILE /data/ai-phone/api-store.sqlite
REMOTE
fi

remote_compose "up -d --no-build --remove-orphans"
if [[ "${MIGRATE_SQLITE:-false}" == "true" ]]; then
  migration_services_stopped=false
  trap - ERR
fi
for _ in {1..60}; do
  if curl -fsS "$API_STATUS_URL" >/dev/null 2>&1 &&
     curl -fsS "$GATEWAY_STATUS_URL" >/dev/null 2>&1 &&
     NO_PROXY='*' no_proxy='*' curl -fsS "$CALL_PUBLIC_BASE_URL/health" >/dev/null 2>&1; then
    if [[ "${MIGRATE_SQLITE:-false}" == "true" ]]; then
      remote_compose "exec -T wujie-ai npm run storage:check -- /data/ai-phone/api-store.sqlite"
    fi
    if wait_for_wujie_container_health; then
      if wait_for_translation_agent_stability; then
        ssh "$REMOTE_HOST" \
          "set -euo pipefail; \
           image_tag_file=\$(mktemp '$REMOTE_RUNTIME/.ai-phone-image-tag.XXXXXX'); \
           printf '%s\\n' '$IMAGE_TAG' > \"\$image_tag_file\"; \
           chmod 600 \"\$image_tag_file\"; \
           mv \"\$image_tag_file\" '$REMOTE_RUNTIME/ai-phone-image-tag'"
        status
        exit 0
      fi
    fi
    break
  fi
  sleep 2
done
remote_compose "ps"
remote_compose "logs --tail=120 wujie-ai"
echo "ai phone server deployment did not become healthy" >&2
exit 1
