export function modelConfigPage(kind:"public"|"private"="public"){
const isPrivate=kind==="private",title=isPrivate?"私有云配置":"公共模型配置",root=`/models/${kind}-config`,prefix=kind.toUpperCase();
return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title} · 无界AI</title><style>
:root{color-scheme:light;font-family:system-ui,-apple-system,"PingFang SC",sans-serif;color:#193047;background:#f3f6fa}*{box-sizing:border-box}body{margin:0}main{max-width:1320px;margin:auto;padding:32px 24px 100px}h1{font-size:28px;margin:8px 0}h2{font-size:20px;margin:0}p{line-height:1.7;color:#52667a}header{display:flex;justify-content:space-between;gap:20px;align-items:center}.brand{font-size:12px;font-weight:700;letter-spacing:2px;color:#087e8b}.badge{padding:7px 12px;border-radius:20px;background:#e3eff6;font-size:12px;white-space:nowrap}.note{padding:16px 18px;border:1px solid #cfdfed;border-radius:12px;background:#edf5fc;font-size:13px;line-height:1.8}.auth{display:flex;align-items:end;gap:10px;margin:22px 0}.auth label{flex:1;max-width:540px}label{display:block;font-size:12px;font-weight:600;color:#43586c}input,select,textarea{display:block;width:100%;margin-top:6px;padding:10px;border:1px solid #c9d4df;border-radius:7px;background:white;color:#193047;font:inherit;font-size:13px}input[type=checkbox]{display:inline;width:auto;margin:0 7px 0 0}input:focus,select:focus,textarea:focus{outline:2px solid #64b9be;outline-offset:1px}button{border:1px solid #c0ccd8;border-radius:8px;background:white;color:#25475c;padding:11px 16px;font-weight:600;cursor:pointer}button.primary{color:white;background:#087e8b;border-color:#087e8b}button:disabled{opacity:.5;cursor:default}.cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.card{background:white;border:1px solid #dce4ec;border-radius:15px;padding:22px;box-shadow:0 4px 14px #263a5010}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.stage{font-size:12px;color:#6b7b8b}.fields{display:grid;grid-template-columns:1fr 1fr;gap:15px;margin-top:16px}.wide{grid-column:1/-1}.secrets{margin-top:18px;border-top:1px solid #e2e9ef;padding-top:16px}.secrets label{margin-bottom:12px}small{display:block;color:#697d90;line-height:1.7;font-size:12px;margin-top:8px}.status{min-height:40px;padding:12px 0;font-size:13px;color:#516a7e;white-space:pre-wrap}.error{color:#a62323}.ok{color:#146949}footer{position:fixed;bottom:0;left:0;right:0;background:#ffffffed;border-top:1px solid #d9e3ec;padding:16px 24px;display:flex;gap:12px;align-items:center;justify-content:center;backdrop-filter:blur(8px)}footer span{font-size:12px;color:#657a8c}textarea{resize:vertical;min-height:115px}@media(max-width:1000px){.cards{grid-template-columns:1fr}main{max-width:680px}header{align-items:start}.auth{flex-wrap:wrap}.auth label{min-width:100%}footer{flex-wrap:wrap;padding:12px}h1{font-size:23px}}
.mode-nav{display:flex;gap:10px;margin:0 0 22px}.mode-nav a{padding:10px 16px;border:1px solid #cad7e2;border-radius:8px;text-decoration:none;color:#37556c;background:white}.mode-nav a[aria-current=page]{background:#087e8b;color:white;border-color:#087e8b}
</style></head><body data-config-root="${root}" data-config-kind="${kind}"><main><nav class="mode-nav" aria-label="配置页面切换"><a href="/models/public-config" ${!isPrivate?'aria-current="page"':''}>公有云配置</a><a href="/models/private-config" ${isPrivate?'aria-current="page"':''}>私有云配置</a></nav><header><div><div class="brand">无界AI / ${prefix} MODELS</div><h1>${title}</h1><p>${isPrivate?'配置自托管 ASR、LM Studio / Hy-MT2 翻译与 HTTP / 流式 TTS。':'ASR、翻译、TTS 独立选择供应商与模型，保留现有手机端和私有版。'}</p></div><span id="revision" class="badge">尚未加载服务端配置</span></header>
<div class="note">这是服务端管理入口。密钥加密保存在服务器，回读不返回密钥；不要填写普通账号登录 Token。<br>${isPrivate?'私有云与公有云分开保存。支持内网 HTTP/HTTPS，健康/flush/流式地址与服务地址须同源；不修改现有1.0路由文件，不启停服务。':'保存仅更新配置，不调用模型、不计费、不启用线上流量。语种跟随当前会话，不在此写死。'}供应商、认证方式或服务域名改变后需重新填写凭据。</div>
<section class="auth"><label>管理凭据（INTERNAL_API_SECRET，仅当前页面内存）<input id="admin" type="password" autocomplete="off" placeholder="输入服务端管理凭据"></label><button id="load" disabled>加载配置</button><button id="lock">锁定并清空页面凭据</button></section>
<div id="message" role="status" class="status">准备配置表单…</div><section id="cards" class="cards" aria-label="三组件${title}"></section>
<small>服务端需设置 ${prefix}_MODEL_CONFIG_FILE（独立绝对路径）和 ${prefix}_MODEL_CONFIG_KEY（64位十六进制加密密钥）${isPrivate?'，私有配置身份使用 PRIVATE_MODEL_CONFIG_DEPLOYMENT_ID，无需开启公有模式':''}。主密钥不在此页面输入，也不会随配置回读。当前保存状态不代表服务已通过运行验收。</small>
</main><footer><button id="save" class="primary" disabled>校验字段并保存配置</button><button id="export" disabled>导出无密钥配置</button><span id="footnote">未连接 · 不会发起模型请求</span></footer><script src="${root}/editor.js" defer></script></body></html>`;
}
export const publicModelConfigPage=modelConfigPage("public");

export const publicModelConfigScript=String.raw`'use strict';
const names={asr:'语音识别 ASR',translation:'文本翻译',tts:'语音合成 TTS'},secretNames={apiKey:'API Key',secretId:'SecretId',secretKey:'SecretKey',serviceAccountJson:'服务账号 JSON（含私钥，仅加密保存）'};
const configRoot=document.body.dataset.configRoot,configKind=document.body.dataset.configKind;
const fields=[['endpoint','API Base URL / 服务地址','wide'],['modelId','模型 ID / 引擎类型','wide'],['region','区域 / Region'],['appId','腾讯 AppID'],['projectId','Google Project ID'],['location','Google Location'],['recognizer','Google Recognizer ID'],['voice','音色 / Voice ID（腾讯填 VoiceType）'],['timeoutMs','请求超时（毫秒）'],['maxTokens','翻译最大输出 Tokens'],['sampleRate','PCM 采样率']];
let catalog,draft,status={},revision=0,loaded=false,busy=false,lastPublic=null,generation=0;
const $=id=>document.getElementById(id);
function message(text,bad=false){$('message').textContent=text;$('message').className='status '+(bad?'error':'ok');}
function secure(){return location.protocol==='https:'||['localhost','127.0.0.1','[::1]'].includes(location.hostname);}
function selected(c){return catalog.protocols.find(p=>p.id===draft[c].protocol);}
function control(label,id,value,wide=false){const wrap=document.createElement('label');wrap.textContent=label;if(wide)wrap.className='wide';const input=document.createElement('input');input.id=id;input.value=value;wrap.append(input);return {wrap,input};}
function select(label,id,items,value,wide=false){const r=control(label,id,'',wide),s=document.createElement('select');s.id=id;for(const x of items){const o=document.createElement('option');o.value=x.id;o.textContent=x.label;s.append(o);}s.value=value;r.input.replaceWith(s);return {wrap:r.wrap,input:s};}
function capture(c){const card=$('card-'+c);if(!card)return;const locales=$(c+'-languageLocales');let mapping;if(locales){try{mapping=JSON.parse(locales.value||'{}');}catch{throw Error('Google ASR 语言区域映射必须是JSON对象');}}for(const k of Object.keys(draft[c])){if(k==='languageLocales')continue;const el=$(c+'-'+k);if(el)draft[c][k]=k==='enabled'?el.checked:['timeoutMs','maxTokens','sampleRate'].includes(k)?Number(el.value):el.value.trim();}if(locales)draft[c].languageLocales=mapping;}
function card(c){const v=draft[c],p=selected(c);const root=document.createElement('article');root.className='card';root.id='card-'+c;
 const top=document.createElement('div');top.className='top';const title=document.createElement('h2');title.textContent=names[c];top.append(title);const check=document.createElement('label');const toggle=document.createElement('input');toggle.type='checkbox';toggle.id=c+'-enabled';toggle.checked=v.enabled;check.append(toggle,document.createTextNode('启用配置'));top.append(check);root.append(top);
 const form=document.createElement('div');form.className='fields';const vendor=select(catalog.vendorLabel||'供应商',c+'-vendor',catalog.vendors.filter(v=>catalog.protocols.some(p=>p.component===c&&p.vendor===v.id)),v.vendor,true);form.append(vendor.wrap);
 const protocol=select('接口协议（不自动转换协议）',c+'-protocol',catalog.protocols.filter(x=>x.vendor===v.vendor&&x.component===c).map(x=>({id:x.id,label:x.label})),v.protocol,true);form.append(protocol.wrap);
 const auth=select('认证方式',c+'-authKind',p.auth.map(id=>({id,label:catalog.authLabels[id]})),v.authKind,true);form.append(auth.wrap);
 for(const [key,label,wide]of (catalog.editorFields||fields)){if(['appId','projectId','location','recognizer','voice','flushEndpoint','streamEndpoint'].includes(key)&&!p.fields.includes(key))continue;if(key==='maxTokens'&&c!=='translation')continue;if(key==='sampleRate'&&c==='translation')continue;
   const r=key==='sampleRate'?select(label,c+'-'+key,[{id:'16000',label:'16000 Hz'},{id:'24000',label:'24000 Hz'}],String(v[key])):control(label,c+'-'+key,v[key],Boolean(wide));
   if(key==='timeoutMs'||key==='maxTokens'){r.input.type='number';r.input.min=key==='timeoutMs'?'250':'1';r.input.max=key==='timeoutMs'?'120000':'16384';}
   if(key==='endpoint')r.input.placeholder=p.endpointPlaceholder||(p.scheme==='wss:'?'wss://供应商服务地址':'https://供应商 API Base URL');
   if(key==='modelId')r.input.placeholder=p.modelPlaceholder||(p.modelRequired?'手动输入模型 ID，不预设固定模型':'可选；该接口可由音色/VoiceType决定');form.append(r.wrap);
 }
 if(p.fields.includes('languageLocales')){const wrap=document.createElement('label');wrap.className='wide';wrap.textContent='Google ASR 语言区域映射（JSON，随会话源语言取值）';const area=document.createElement('textarea');area.id=c+'-languageLocales';area.value=JSON.stringify(v.languageLocales||{},null,2);area.placeholder='{"zh":"cmn-Hans-CN","en":"en-US"}';wrap.append(area);form.append(wrap);}
 root.append(form);const creds=document.createElement('div');creds.className='secrets';
 for(const key of catalog.credentialFields[v.authKind]){const r=control(secretNames[key],c+'-secret-'+key,'');r.input.type='password';r.input.autocomplete='new-password';r.input.dataset.secret='true';r.input.placeholder=status[c]?.credentialsPresent?.[key]?'已配置；留空保留（换供应商/域名需重填）':'尚未配置';
   if(key==='serviceAccountJson'){const area=document.createElement('textarea');area.id=r.input.id;area.dataset.secret='true';area.autocomplete='off';area.placeholder=r.input.placeholder;r.input.replaceWith(area);}creds.append(r.wrap);}
 if(v.authKind==='google_adc'){const hint=document.createElement('small');hint.textContent='使用服务器显式配置的 PUBLIC_GOOGLE_ADC_FILE（仅 service_account / authorized_user）；不读取本机登录或云主机元数据。页面不获取或验证令牌。';creds.append(hint);}
 const clear=document.createElement('label'),box=document.createElement('input');box.type='checkbox';box.id=c+'-clear';clear.append(box,document.createTextNode('本次保存时清除此组件已有凭据'));creds.append(clear);
 const state=document.createElement('small');state.className='stage';state.textContent=({disabled:'未启用配置',incomplete:'已保存但字段不完整',configured_not_verified:'已配置 · 尚未验证/激活'})[status[c]?.state]||'未保存草稿';if(status[c]?.missing?.length)state.textContent+='：'+status[c].missing.join(', ');creds.append(state);root.append(creds);
 vendor.input.onchange=()=>{try{capture(c);}catch(e){vendor.input.value=v.vendor;message(e.message,true);return;}const newVendor=vendor.input.value,np=catalog.protocols.find(x=>x.vendor===newVendor&&x.component===c);Object.assign(draft[c],{vendor:newVendor,protocol:np.id,authKind:np.auth[0]});delete draft[c].languageLocales;for(const key of ['endpoint','modelId','appId','projectId','location','recognizer','voice','healthUrl','flushEndpoint','streamEndpoint'])if(key in draft[c])draft[c][key]='';status[c]={};root.replaceWith(card(c));message('模型服务已更改，请重新填写地址、模型及凭据。');};
 protocol.input.onchange=()=>{try{capture(c);}catch(e){protocol.input.value=v.protocol;message(e.message,true);return;}const np=selected(c);if(!np.fields.includes('languageLocales'))delete draft[c].languageLocales;draft[c].authKind=np.auth[0];draft[c].endpoint='';status[c]={};root.replaceWith(card(c));message('协议已更改，请核对服务地址及认证方式。');};
 auth.input.onchange=()=>{try{capture(c);}catch(e){auth.input.value=v.authKind;message(e.message,true);return;}status[c]={};root.replaceWith(card(c));message('认证方式已更改，请填写对应凭据。');};return root;
}
function render(){$('cards').replaceChildren(...Object.keys(names).map(card));$('revision').textContent=loaded?'配置版本 r'+revision:'尚未加载服务端配置';$('save').disabled=!loaded||busy||!secure();$('export').disabled=!lastPublic||busy;$('load').disabled=busy;}
async function api(method,body){const token=$('admin').value.trim();if(!token)throw Error('请先输入管理凭据');if(!secure())throw Error('管理操作仅允许 HTTPS 或本机回环地址');const r=await fetch(configRoot+'/data',{method,cache:'no-store',redirect:'error',headers:{authorization:'Bearer '+token,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(r.status===409?'配置已被其他管理端修改；请先重新加载，再重新编辑。':r.status===401?'管理凭据不正确或未配置':data.error?.code?.endsWith('_config_storage_not_ready')?'服务端尚未设置部署身份、配置文件路径或加密主密钥':data.error?.code||'配置请求失败');return data;}
async function load(){const epoch=++generation;busy=true;render();try{const data=await api('GET');if(epoch!==generation)return;draft=data.components;revision=data.revision;status=data.status;loaded=true;lastPublic=data;message('已加载。密钥不回读；留空保留已有密钥。');$('footnote').textContent='服务端配置 r'+revision+' · 未激活模型运行';}catch(e){if(epoch===generation)message(e.message,true);}finally{if(epoch===generation){busy=false;render();}}}
$('load').onclick=load;
$('lock').onclick=()=>{generation++;busy=false;$('admin').value='';loaded=false;lastPublic=null;status={};if(catalog)draft=structuredClone(catalog.defaults.components);revision=0;if(catalog)render();message('已锁定并清空页面凭据；已发出的保存可能完成，服务器配置不会自动撤销。');$('footnote').textContent='未连接 · 不会发起模型请求';};
$('save').onclick=async()=>{if(!loaded||busy)return;const epoch=++generation,credentials={},clearCredentials=[];for(const c of Object.keys(names)){capture(c);credentials[c]={};for(const key of catalog.credentialFields[draft[c].authKind]){const value=$(c+'-secret-'+key)?.value;if(value)credentials[c][key]=value;}if($(c+'-clear').checked)clearCredentials.push(c);}busy=true;render();try{const data=await api('PUT',{expectedRevision:revision,components:draft,credentials,clearCredentials});if(epoch!==generation)return;draft=data.components;revision=data.revision;status=data.status;lastPublic=data;message('配置已加密保存。没有调用模型，也没有启用线上流量。');$('footnote').textContent='已保存 r'+revision+' · 等待适配与运行验收';}catch(e){if(epoch===generation)message(e.message+'；为保护凭据，密码输入已清空，必要时请重新填写。',true);}finally{if(epoch===generation){busy=false;render();}}};
$('export').onclick=()=>{if(!lastPublic)return;const blob=new Blob([JSON.stringify(lastPublic,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='wujie-'+configKind+'-model-config-no-secrets.json';link.click();URL.revokeObjectURL(url);};
fetch(configRoot+'/catalog',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('无法加载配置目录');return r.json();}).then(data=>{catalog=data;draft=structuredClone(data.defaults.components);render();message(secure()?'先加载服务器配置，再编辑三个组件。':'请通过 HTTPS 或本机地址打开管理页面。',!secure());}).catch(e=>message(e.message,true));
`;
